-- BisManagerConfig.lua
-- Configuration UI for the BisManager addon (redesigned 4-tab layout)

local BisManager = _G.BisManager
if not BisManager then
    return
end

local addonName, addon = ...
local L = addon.ResolveLocale()
local SLOT_DEFINITIONS = BisManager.SLOT_DEFINITIONS
local SLOT_BY_KEY = BisManager.SLOT_BY_KEY
local DEFAULT_ICON = BisManager.DEFAULT_ICON or 134400
local DELETE_ICON = "Interface\\AddOns\\BisManager\\Assets\\Delete"

------------------------------------------------------------------------
-- State
------------------------------------------------------------------------

local configFrame
local selectedSlotKey
local slotButtons = {}
local itemRows = {}
local MAX_ITEM_ROWS = 10
local ITEM_ROW_HEIGHT = 56
local MAX_SEARCH_ROWS = 5
local statsRows = {}
local MAX_STATS_ROWS = 30
local profileListButtons = {}
local MAX_PROFILE_ROWS = 12

------------------------------------------------------------------------
-- Forward declarations
------------------------------------------------------------------------

local RefreshSlotList, RefreshDetailPanel, RefreshSettingsPanel, RefreshImportPanel, RefreshProfilesPanel, RefreshStatsPanel, SwitchTab, CreateConfigFrame

local function GetStatsSlotLabel(slotDef, entryIndex)
    if slotDef.key == "FINGER" then
        return entryIndex == 1 and L["stats_finger_1"] or L["stats_finger_2"]
    end
    if slotDef.key == "TRINKET" then
        return entryIndex == 1 and L["stats_trinket_1"] or L["stats_trinket_2"]
    end
    return slotDef.label
end

local function GetStatsLayout(contentWidth)
    local width = math.max(contentWidth or 620, 620)
    local slotX = 4
    local slotW = 74
    local iconX = 84
    local iconW = 18
    local itemX = 108
    local availableStatsWidth = math.max(width - itemX - 12, 360)
    local itemW = math.max(170, math.floor(availableStatsWidth * 0.38))
    local statX = itemX + itemW
    local statW = math.max(72, math.floor((width - statX - 8) / 4))

    return {
        width = width,
        slotX = slotX,
        slotW = slotW,
        iconX = iconX,
        iconW = iconW,
        itemX = itemX,
        itemW = itemW,
        statX = statX,
        statW = statW,
    }
end

------------------------------------------------------------------------
-- Confirmation popup
------------------------------------------------------------------------

StaticPopupDialogs["BisManager_CONFIRM_CLEAR_ALL"] = {
    text = L["popup_clear"], button1 = L["popup_yes"], button2 = L["popup_no"],
    OnAccept = function()
        if BisManager and BisManager.db then
            BisManager:ClearActiveProfile()
            BisManager:RefreshAll()
            if RefreshSlotList then RefreshSlotList() end
            if RefreshDetailPanel then RefreshDetailPanel() end
        end
    end,
    timeout = 0, whileDead = true, hideOnEscape = true, preferredIndex = 3,
}

StaticPopupDialogs["BisManager_CONFIRM_RESET_PROFILES"] = {
    text = L["popup_reset_profiles"], button1 = L["popup_yes"], button2 = L["popup_no"],
    OnAccept = function()
        if BisManager and BisManager.db then
            BisManager.db.profiles = {}
            BisManager.db.activeProfile = "Default"
            BisManager:GetOrCreateProfile("Default")
            if BisManager.AutoCreateBiSProfiles then
                BisManager:AutoCreateBiSProfiles()
            end
            BisManager:RefreshAll()
            if RefreshSlotList then RefreshSlotList() end
            if RefreshDetailPanel then RefreshDetailPanel() end
            if RefreshImportPanel then RefreshImportPanel() end
            if RefreshProfilesPanel then RefreshProfilesPanel() end
        end
    end,
    timeout = 0, whileDead = true, hideOnEscape = true, preferredIndex = 3,
}

StaticPopupDialogs["BisManager_CONFIRM_RESET_GENERATED"] = {
    text = L["popup_reset_generated"], button1 = L["popup_yes"], button2 = L["popup_no"],
    OnAccept = function()
        if BisManager and BisManager.db then
            -- Remove only auto-generated profiles
            for name, profile in pairs(BisManager.db.profiles) do
                if profile.autoGenerated then
                    BisManager.db.profiles[name] = nil
                end
            end
            if BisManager.AutoCreateBiSProfiles then
                BisManager:AutoCreateBiSProfiles()
            end
            -- Ensure active profile still exists
            if not BisManager.db.profiles[BisManager.db.activeProfile] then
                BisManager.db.activeProfile = next(BisManager.db.profiles) or "Default"
                BisManager:GetOrCreateProfile(BisManager.db.activeProfile)
            end
            BisManager:RefreshAll()
            if RefreshSlotList then RefreshSlotList() end
            if RefreshDetailPanel then RefreshDetailPanel() end
            if RefreshProfilesPanel then RefreshProfilesPanel() end
        end
    end,
    timeout = 0, whileDead = true, hideOnEscape = true, preferredIndex = 3,
}

------------------------------------------------------------------------
-- Helpers
------------------------------------------------------------------------

local BMUI = BisManager.UI
if not BMUI then
    return
end

local BD_TEMPLATE = BMUI.BD_TEMPLATE
local EDITBOX_TEMPLATE = BMUI.EDITBOX_TEMPLATE
local UI = BMUI.colors
local ApplyBackdrop = BMUI.ApplyBackdrop
local AddSoftShadow = BMUI.AddSoftShadow
local SkinEditBox = BMUI.SkinEditBox
local SkinCheckButton = BMUI.SkinCheckButton
local SkinScrollFrame = BMUI.SkinScrollFrame
local SkinButton = BMUI.SkinButton
local CreateCustomButton = BMUI.CreateButton
local SuccessBtn = BMUI.SuccessBtn
local InfoBtn = BMUI.InfoBtn
local WarningBtn = BMUI.WarningBtn
local DangerBtn = BMUI.DangerBtn
local SkinPanel = BMUI.SkinPanel
local CreateBentoCard = BMUI.CreateCard
local CreateSimpleSlider = BMUI.CreateSlider
local PADDING = UI.layout.padding
local GAP = UI.layout.gap
local RADIUS = UI.layout.radius

local function SkinDeleteIcon(button, iconSize)
    SkinButton(button, "danger")
    button.trashIcon = button.trashIcon or button:CreateTexture(nil, "ARTWORK")
    button.trashIcon:ClearAllPoints()
    button.trashIcon:SetPoint("CENTER")
    button.trashIcon:SetSize(iconSize or 13, iconSize or 13)
    button.trashIcon:SetTexture(DELETE_ICON)
    button.trashIcon:SetVertexColor(1, 0.78, 0.82, 0.96)
    return button
end

local function CreateEquippedItemLine(parent, topOffset)
    local line = CreateFrame("Frame", nil, parent)
    line:SetPoint("TOPLEFT", PADDING, topOffset)
    line:SetPoint("RIGHT", -PADDING, 0)
    line:SetHeight(16)

    line.label = line:CreateFontString(nil, "OVERLAY", "GameFontHighlight")
    line.label:SetPoint("LEFT", 0, 0)
    line.label:SetJustifyH("LEFT")
    line.label:SetWordWrap(false)
    line.label:SetText(L["equipped_label"])

    line.status = line:CreateFontString(nil, "OVERLAY", "GameFontHighlight")
    line.status:SetPoint("LEFT", line.label, "RIGHT", 0, 0)
    line.status:SetJustifyH("LEFT")
    line.status:SetWordWrap(false)

    line.iconBtn = CreateFrame("Button", nil, line)
    line.iconBtn:SetSize(16, 16)
    line.iconBtn:SetPoint("LEFT", line.status, "RIGHT", 4, 0)
    line.icon = line.iconBtn:CreateTexture(nil, "ARTWORK")
    line.icon:SetAllPoints()
    line.icon:SetTexCoord(0.08, 0.92, 0.08, 0.92)

    line.name = line:CreateFontString(nil, "OVERLAY", "GameFontHighlight")
    line.name:SetPoint("LEFT", line.iconBtn, "RIGHT", 6, 0)
    line.name:SetPoint("RIGHT", 0, 0)
    line.name:SetJustifyH("LEFT")
    line.name:SetWordWrap(false)
    line.nameMeasure = line:CreateFontString(nil, "OVERLAY", "GameFontHighlight")
    line.nameMeasure:Hide()

    line.nameBtn = CreateFrame("Button", nil, line)
    line.nameBtn:SetPoint("LEFT", line.name, "LEFT", 0, 0)
    line.nameBtn:SetHeight(16)
    line.nameBtn:SetWidth(1)

    local function ShowTooltip(self)
        if not self.itemLink then
            return
        end
        GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
        GameTooltip:SetHyperlink(self.itemLink)
        GameTooltip:Show()
    end

    line.iconBtn:SetScript("OnEnter", ShowTooltip)
    line.iconBtn:SetScript("OnLeave", GameTooltip_Hide)
    line.nameBtn:SetScript("OnEnter", ShowTooltip)
    line.nameBtn:SetScript("OnLeave", GameTooltip_Hide)

    return line
end

local function SetEquippedItemLine(line, itemID, itemLink, prefixText, itemText, emptyText)
    if not line then
        return
    end

    if itemID and itemLink then
        line.status:SetText(prefixText or "")
        line.icon:SetTexture(BisManager:GetItemIcon(itemID))
        line.iconBtn.itemLink = itemLink
        line.nameBtn.itemLink = itemLink
        line.iconBtn:Show()
        line.name:SetText(itemText or itemLink)
        line.nameMeasure:SetText(itemText or itemLink)
        line.name:SetTextColor(1, 1, 1)
        line.nameBtn:SetWidth(math.max(1, math.min(line.nameMeasure:GetStringWidth() + 4, 420)))
    else
        line.status:SetText("")
        line.iconBtn.itemLink = nil
        line.nameBtn.itemLink = nil
        line.iconBtn:Hide()
        line.name:SetText(emptyText or "")
        line.nameMeasure:SetText(emptyText or "")
        line.name:SetTextColor(1, 1, 1)
        line.nameBtn:SetWidth(math.max(1, math.min(line.nameMeasure:GetStringWidth() + 4, 420)))
    end
end

local function OpenExternalUrl(url)
    BisManager:OpenExternalUrl(url, configFrame and configFrame.profilesPanel, L["external_url_title"])
end

local function SplitGeneratedProfileName(name)
    local provider, mode = (name or ""):match("^(.-)%s+%-%s+(.+)$")
    if provider and mode then
        return provider, mode
    end
    return name or "", ""
end

local function NormalizeSearchText(value)
    return tostring(value or ""):lower():gsub("^%s+", ""):gsub("%s+$", "")
end

local function GetPlainItemName(itemID)
    local name, link = GetItemInfo(itemID)
    if link and link ~= "" then
        return link:gsub("|c%x%x%x%x%x%x%x%x", ""):gsub("|r", ""):gsub("%[", ""):gsub("%]", "")
    end
    return name
end

local function PreloadSlotSearchItems(slotKey)
    local presets = BisManager.GetPlayerPresets and BisManager:GetPlayerPresets()
    if not presets then
        return
    end
    for _, presetData in pairs(presets) do
        local ids = type(presetData) == "table" and presetData[slotKey]
        if type(ids) == "table" then
            for _, itemID in ipairs(ids) do
                itemID = tonumber(itemID)
                if itemID and C_Item and C_Item.RequestLoadItemDataByID then
                    C_Item.RequestLoadItemDataByID(itemID)
                end
            end
        end
    end
end

local function GetSlotSearchResults(slotKey, query, maxResults)
    local needle = NormalizeSearchText(query)
    local results = {}
    if not slotKey or needle == "" then
        return results
    end

    local presets = BisManager.GetPlayerPresets and BisManager:GetPlayerPresets()
    if not presets then
        return results
    end

    local byID = {}
    for presetName, presetData in pairs(presets) do
        local ids = type(presetData) == "table" and presetData[slotKey]
        if type(ids) == "table" then
            for _, itemID in ipairs(ids) do
                itemID = tonumber(itemID)
                if itemID then
                    local itemName = GetPlainItemName(itemID)
                    local haystack = NormalizeSearchText((itemName or "") .. " " .. itemID)
                    if haystack:find(needle, 1, true) then
                        local entry = byID[itemID]
                        if not entry then
                            entry = { itemID = itemID, name = itemName or ("item:" .. itemID), sources = {} }
                            byID[itemID] = entry
                            results[#results + 1] = entry
                        elseif itemName then
                            entry.name = itemName
                        end
                        entry.sources[#entry.sources + 1] = presetName
                    elseif not itemName and C_Item and C_Item.RequestLoadItemDataByID then
                        C_Item.RequestLoadItemDataByID(itemID)
                    end
                end
            end
        end
    end

    table.sort(results, function(a, b)
        return (a.name or "") < (b.name or "")
    end)

    if maxResults and #results > maxResults then
        for index = #results, maxResults + 1, -1 do
            results[index] = nil
        end
    end
    return results
end

local function CreateProfileDropdown(parent)
    local container = CreateFrame("Frame", nil, parent)
    container:SetSize(280, 26)

    local label = container:CreateFontString(nil, "OVERLAY", "GameFontNormal")
    label:SetPoint("LEFT", 0, 0); label:SetText(L["profile_select"])

    local dropdown = CreateFrame("Frame", nil, container, BD_TEMPLATE)
    dropdown:SetSize(180, 24); dropdown:SetPoint("LEFT", label, "RIGHT", 6, 0)
    ApplyBackdrop(dropdown, UI.input, UI.line, UI.round.input)

    dropdown.text = dropdown:CreateFontString(nil, "OVERLAY", "GameFontHighlight")
    dropdown.text:SetPoint("LEFT", 8, 0); dropdown.text:SetPoint("RIGHT", -20, 0)
    dropdown.text:SetJustifyH("LEFT")

    local arrowBtn = CreateFrame("Button", nil, dropdown, BD_TEMPLATE)
    arrowBtn:SetSize(20, 24); arrowBtn:SetPoint("RIGHT", 0, 0)
    arrowBtn.text = arrowBtn:CreateFontString(nil, "OVERLAY", "GameFontNormal")
    arrowBtn.text:SetAllPoints(); arrowBtn.text:SetText("v")
    SkinButton(arrowBtn)

    local menuFrame = CreateFrame("Frame", "BisManagerProfileMenu", UIParent, BD_TEMPLATE)
    menuFrame:SetFrameStrata("TOOLTIP"); menuFrame:SetClampedToScreen(true)
    ApplyBackdrop(menuFrame, UI.island, UI.line, UI.round.card)
    AddSoftShadow(menuFrame, 0.26)
    menuFrame:Hide()
    menuFrame.buttons = {}

    local function CloseMenu() menuFrame:Hide() end

    local function OpenMenu()
        if menuFrame:IsShown() then CloseMenu(); return end
        local names = BisManager:GetProfileNames()
        local bh = 20
        for i, btn in ipairs(menuFrame.buttons) do btn:Hide() end
        for i, name in ipairs(names) do
            local btn = menuFrame.buttons[i]
            if not btn then
                btn = CreateFrame("Button", nil, menuFrame, BD_TEMPLATE)
                btn:SetHeight(bh); btn.text = btn:CreateFontString(nil, "OVERLAY", "GameFontHighlight")
                btn.text:SetPoint("LEFT", 8, 0)
                btn.text:SetPoint("RIGHT", -8, 0)
                btn.text:SetJustifyH("LEFT")
                ApplyBackdrop(btn, UI.slate, UI.lineSoft, UI.round.row)
                btn.hl = btn:CreateTexture(nil, "HIGHLIGHT")
                btn.hl:SetPoint("TOPLEFT", 4, -3)
                btn.hl:SetPoint("BOTTOMRIGHT", -4, 3)
                btn.hl:SetColorTexture(0.36, 0.78, 1, 0.2)
                menuFrame.buttons[i] = btn
            end
            btn:SetPoint("TOPLEFT", 4, -(i - 1) * bh - 4)
            btn:SetPoint("RIGHT", menuFrame, "RIGHT", -4, 0)
            local isActive = (name == BisManager:GetActiveProfileName())
            btn.text:SetText(isActive and ("|cff4cff4c" .. name .. "|r") or name)
            btn:SetScript("OnClick", function()
                BisManager:SetActiveProfile(name)
                dropdown.text:SetText(name)
                CloseMenu()
                if RefreshSlotList then RefreshSlotList() end
                if RefreshDetailPanel then RefreshDetailPanel() end
                if RefreshStatsPanel then RefreshStatsPanel() end
            end)
            btn:Show()
        end
        local h = #names * bh + 8
        menuFrame:SetSize(180, h)
        menuFrame:ClearAllPoints()
        menuFrame:SetPoint("TOPLEFT", dropdown, "BOTTOMLEFT", 0, -2)
        menuFrame:Show()
    end

    arrowBtn:SetScript("OnClick", OpenMenu)
    dropdown:SetScript("OnMouseDown", OpenMenu)
    menuFrame:SetScript("OnLeave", function(self)
        if not self:IsMouseOver() then CloseMenu() end
    end)

    container.dropdown = dropdown
    container.Refresh = function()
        dropdown.text:SetText(BisManager:GetActiveProfileName())
    end
    container:Refresh()
    return container
end

------------------------------------------------------------------------
-- Slot button (left panel)
------------------------------------------------------------------------

local function CreateSlotButton(parent, index, slotDef)
    local btn = CreateFrame("Button", nil, parent, BD_TEMPLATE)
    btn:SetSize(222, 38); btn:SetPoint("TOPLEFT", 0, -(index - 1) * (38 + GAP))
    btn.slotKey = slotDef.key
    ApplyBackdrop(btn, { 0.085, 0.102, 0.126, 0.78 }, UI.lineSoft, UI.round.row)

    btn.bg = btn:CreateTexture(nil, "BACKGROUND"); btn.bg:SetAllPoints(); btn.bg:ClearAllPoints()
    btn.bg:SetPoint("TOPLEFT", 5, -4)
    btn.bg:SetPoint("BOTTOMRIGHT", -5, 4)
    btn.bg:SetColorTexture(0.10, 0.12, 0.15, 0.18)
    btn.selectedBg = btn:CreateTexture(nil, "BORDER"); btn.selectedBg:SetAllPoints(); btn.selectedBg:ClearAllPoints()
    btn.selectedBg:SetPoint("TOPLEFT", 5, -4)
    btn.selectedBg:SetPoint("BOTTOMRIGHT", -5, 4)
    btn.selectedBg:SetColorTexture(0.08, 0.34, 0.52, 0.70); btn.selectedBg:Hide()
    btn.accent = btn:CreateTexture(nil, "ARTWORK")
    btn.accent:SetPoint("TOPLEFT", 7, -9); btn.accent:SetPoint("BOTTOMLEFT", 7, 9); btn.accent:SetWidth(3)
    btn.accent:SetColorTexture(0, 0, 0, 0); btn.accent:Hide()
    btn.hl = btn:CreateTexture(nil, "HIGHLIGHT")
    btn.hl:SetPoint("TOPLEFT", 5, -4); btn.hl:SetPoint("BOTTOMRIGHT", -5, 4)
    btn.hl:SetColorTexture(UI.blue[1], UI.blue[2], UI.blue[3], 0.10)
    btn.separator = btn:CreateTexture(nil, "BORDER")
    btn.separator:SetPoint("BOTTOMLEFT", 10, 0)
    btn.separator:SetPoint("BOTTOMRIGHT", -8, 0)
    btn.separator:SetHeight(1)
    btn.separator:SetColorTexture(1, 1, 1, 0.035)

    btn.dot = btn:CreateTexture(nil, "OVERLAY"); btn.dot:SetSize(8, 8); btn.dot:SetPoint("LEFT", 8, 0)
    btn.dot:SetColorTexture(0.4, 0.4, 0.4, 1)

    btn.icon = btn:CreateTexture(nil, "ARTWORK"); btn.icon:SetSize(24, 24)
    btn.icon:SetPoint("LEFT", btn.dot, "RIGHT", 6, 0)
    btn.icon:SetTexCoord(0.08, 0.92, 0.08, 0.92); btn.icon:SetTexture(DEFAULT_ICON)

    btn.label = btn:CreateFontString(nil, "OVERLAY", "GameFontNormal")
    btn.label:SetPoint("TOPLEFT", btn.icon, "TOPRIGHT", 8, -6); btn.label:SetPoint("RIGHT", -52, 0)
    btn.label:SetText(slotDef.label); btn.label:SetJustifyH("LEFT"); btn.label:SetWordWrap(false)


    btn.countBadge = CreateFrame("Frame", nil, btn, BD_TEMPLATE)
    btn.countBadge:SetSize(28, 18)
    btn.countBadge:SetPoint("RIGHT", -8, 0)
    ApplyBackdrop(btn.countBadge, { 0.060, 0.085, 0.108, 0.92 }, UI.lineStrong, UI.round.pill)
    btn.countBadge.text = btn.countBadge:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
    btn.countBadge.text:SetAllPoints()
    btn.countBadge.text:SetJustifyH("CENTER")
    btn.countBadge.text:SetText("")
    btn.countBadge:Hide()

    btn:SetScript("OnClick", function()
        selectedSlotKey = slotDef.key; RefreshSlotList(); RefreshDetailPanel()
    end)
    btn:SetScript("OnEnter", function(self)
        local itemLinks = self.itemLinks
        if not itemLinks or #itemLinks == 0 then
            return
        end
        GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
        GameTooltip:SetHyperlink(itemLinks[1])
        for index = 2, #itemLinks do
            GameTooltip:AddLine(" ")
            GameTooltip:AddLine(itemLinks[index], 1, 1, 1, true)
        end
        GameTooltip:Show()
    end)
    btn:SetScript("OnLeave", GameTooltip_Hide)
    return btn
end

------------------------------------------------------------------------
-- Item row (right panel) - with source display
------------------------------------------------------------------------

local function CreateItemRow(parent, index)
    local row = CreateFrame("Frame", nil, parent, BD_TEMPLATE)
    row:SetSize(380, ITEM_ROW_HEIGHT); row:SetPoint("TOPLEFT", 0, -(index - 1) * (ITEM_ROW_HEIGHT + GAP))
    row:SetPoint("RIGHT", parent, "RIGHT", 0, 0)
    ApplyBackdrop(row, { 0.092, 0.112, 0.138, 0.84 }, { 0.20, 0.38, 0.56, 0.42 }, UI.round.row)

    row.bg = row:CreateTexture(nil, "BACKGROUND")
    row.bg:SetPoint("TOPLEFT", 5, -4)
    row.bg:SetPoint("BOTTOMRIGHT", -5, 4)
    row.bg:SetColorTexture(index % 2 == 0 and 0.12 or 0.10, index % 2 == 0 and 0.14 or 0.12, index % 2 == 0 and 0.17 or 0.15, 0.20)
    row.indexText = row:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
    row.indexText:SetPoint("LEFT", 10, 0); row.indexText:SetWidth(18); row.indexText:SetJustifyH("RIGHT")
    row.indexText:SetTextColor(0.72, 0.78, 0.86)

    row.iconBg = row:CreateTexture(nil, "BORDER")
    row.iconBg:SetSize(34, 34); row.iconBg:SetPoint("LEFT", row.indexText, "RIGHT", 10, 0)
    row.iconBg:SetColorTexture(0.035, 0.045, 0.058, 0.95)
    row.icon = row:CreateTexture(nil, "ARTWORK"); row.icon:SetSize(30, 30)
    row.icon:SetPoint("CENTER", row.iconBg, "CENTER"); row.icon:SetTexCoord(0.08, 0.92, 0.08, 0.92)

    row.nameBtn = CreateFrame("Button", nil, row)
    row.nameBtn:SetPoint("TOPLEFT", row.iconBg, "TOPRIGHT", 10, -1); row.nameBtn:SetPoint("RIGHT", -46, 0)
    row.nameBtn:SetHeight(16)
    row.nameText = row.nameBtn:CreateFontString(nil, "OVERLAY", "GameFontHighlight")
    row.nameText:SetAllPoints(); row.nameText:SetJustifyH("LEFT"); row.nameText:SetWordWrap(false)
    row.nameBtn:SetScript("OnEnter", function(self)
        if row.itemLink then
            GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
            GameTooltip:SetHyperlink(row.itemLink)
            GameTooltip:Show()
        end
    end)
    row.nameBtn:SetScript("OnLeave", GameTooltip_Hide)

    -- Source line
    row.sourceBtnHit = CreateFrame("Button", nil, row)
    row.sourceBtnHit:SetPoint("BOTTOMLEFT", row.iconBg, "BOTTOMRIGHT", 10, 1)
    row.sourceBtnHit:SetHeight(14)
    row.sourceBtnHit:SetWidth(1)
    row.sourceText = row.sourceBtnHit:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
    row.sourceText:SetAllPoints()
    row.sourceText:SetJustifyH("LEFT")
    row.sourceText:SetTextColor(0.76, 0.76, 0.58)
    row.sourceBtnHit:SetScript("OnEnter", function(self)
        if not row.sourceDisplayText or row.sourceDisplayText == "" then
            return
        end
        GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
        GameTooltip:AddLine(row.sourceDisplayText, 1, 1, 1, true)
        if row.sourceCanOpen then
            GameTooltip:AddLine(L["source_tooltip_open_origin"], 0.36, 0.78, 1, true)
            GameTooltip:AddLine(" ")
            if row.sourceUrl and row.sourceUrl ~= "" then
                GameTooltip:AddLine(row.sourceUrl, 0.36, 0.78, 1, true)
            end
        end
        GameTooltip:Show()
    end)
    row.sourceBtnHit:SetScript("OnLeave", GameTooltip_Hide)

    row.removeBtn = CreateFrame("Button", nil, row, BD_TEMPLATE); row.removeBtn:SetSize(26, 26); row.removeBtn:SetPoint("RIGHT", -10, 0)
    SkinDeleteIcon(row.removeBtn, 14)

    row:Hide()
    return row
end

------------------------------------------------------------------------
-- Refresh: slot list
------------------------------------------------------------------------

RefreshSlotList = function()
    if not configFrame or not BisManager.db then return end
    for _, slotDef in ipairs(SLOT_DEFINITIONS) do
        local btn = slotButtons[slotDef.key]
        if btn then
            local isSelected = (selectedSlotKey == slotDef.key)
            btn.selectedBg:SetShown(isSelected)
            if btn.accent then btn.accent:SetShown(isSelected) end
            if btn.SetBackdropBorderColor then
                if isSelected then
                    btn:SetBackdropBorderColor(UI.blue[1], UI.blue[2], UI.blue[3], 0.95)
                else
                    btn:SetBackdropBorderColor(UI.lineSoft[1], UI.lineSoft[2], UI.lineSoft[3], UI.lineSoft[4])
                end
            end
            btn.label:SetTextColor(isSelected and 1 or 0.85, isSelected and 1 or 0.85, isSelected and 1 or 0.85)

            local firstSlotID = slotDef.subSlots and slotDef.subSlots[1].slotID or slotDef.slotID
            local eqID = firstSlotID and GetInventoryItemID("player", firstSlotID) or nil
            btn.icon:SetTexture(eqID and BisManager:GetItemIcon(eqID) or DEFAULT_ICON)
            btn.itemLink = nil
            btn.itemLinks = {}

            if slotDef.subSlots then
                for _, sub in ipairs(slotDef.subSlots) do
                    local equippedLink = GetInventoryItemLink("player", sub.slotID)
                    if equippedLink then
                        btn.itemLinks[#btn.itemLinks + 1] = equippedLink
                    end
                end
            elseif slotDef.slotID then
                btn.itemLink = GetInventoryItemLink("player", slotDef.slotID)
                if btn.itemLink then
                    btn.itemLinks[1] = btn.itemLink
                end
            end

            local entries = BisManager:GetEntries(slotDef.key)
            local hasEntries = entries and #entries > 0
            if hasEntries and #btn.itemLinks == 0 then
                if slotDef.subSlots then
                    for index = 1, math.min(#entries, 2) do
                        local itemLink = BisManager:GetBiSItemLink(entries[index].itemID)
                        if itemLink then
                            btn.itemLinks[#btn.itemLinks + 1] = itemLink
                        end
                    end
                else
                    btn.itemLink = BisManager:GetBiSItemLink(entries[1].itemID)
                    if btn.itemLink then
                        btn.itemLinks[1] = btn.itemLink
                    end
                end
            elseif slotDef.subSlots and #btn.itemLinks < 2 and hasEntries then
                local seenLinks = {}
                for _, link in ipairs(btn.itemLinks) do
                    seenLinks[link] = true
                end
                for index = 1, math.min(#entries, 2) do
                    local itemLink = BisManager:GetBiSItemLink(entries[index].itemID)
                    if itemLink and not seenLinks[itemLink] then
                        btn.itemLinks[#btn.itemLinks + 1] = itemLink
                        seenLinks[itemLink] = true
                    end
                    if #btn.itemLinks >= 2 then
                        break
                    end
                end
            end

            if #btn.itemLinks > 0 then
                btn.itemLink = btn.itemLinks[1]
            end

            if hasEntries then
                local allBis = true
                if slotDef.subSlots then
                    for _, sub in ipairs(slotDef.subSlots) do
                        local subEq = GetInventoryItemID("player", sub.slotID)
                        if not subEq or not BisManager:HasConfiguredItem(slotDef.key, subEq) then allBis = false; break end
                    end
                else
                    allBis = eqID and BisManager:HasConfiguredItem(slotDef.key, eqID) or false
                end
                if allBis then btn.dot:SetColorTexture(0.25, 0.92, 0.35, 1)
                elseif eqID then btn.dot:SetColorTexture(0.95, 0.25, 0.25, 1)
                else btn.dot:SetColorTexture(0.95, 0.75, 0.25, 1) end
            else
                btn.dot:SetColorTexture(0.35, 0.35, 0.35, 1)
            end

            if hasEntries then
                local count = #entries
                btn.countBadge.text:SetText(tostring(count))
                btn.countBadge:Show()
            else
                btn.countBadge:Hide()
            end
        end
    end

    if configFrame and configFrame.ilvlHeader then
        configFrame.ilvlHeader:Hide()
    end

    -- Refresh profile dropdown
    if configFrame.profileDropdown then
        configFrame.profileDropdown:Refresh()
    end
end

local function RefreshSlotSearchResults()
    if not configFrame or not configFrame.rightPanel then return end
    local rp = configFrame.rightPanel
    if not rp.searchPanel or not rp.searchRows or not selectedSlotKey then
        return
    end

    local query = rp.editBox and rp.editBox:GetText() or ""
    if NormalizeSearchText(query) == "" then
        rp.searchPanel:Hide()
        return
    end

    local results = GetSlotSearchResults(selectedSlotKey, query, MAX_SEARCH_ROWS)
    local visibleRows = math.min(#results, MAX_SEARCH_ROWS)
    for i = 1, MAX_SEARCH_ROWS do
        local row = rp.searchRows[i]
        local result = results[i]
        if row and result then
            row.itemID = result.itemID
            row.icon:SetTexture(BisManager:GetItemIcon(result.itemID))
            row.text:SetText(result.name or ("item:" .. result.itemID))
            local sourceText = result.sources[1] or ""
            if #result.sources > 1 then
                sourceText = sourceText .. " +" .. (#result.sources - 1)
            end
            row.meta:SetText(sourceText)
            row:SetScript("OnClick", function(self)
                if not selectedSlotKey or not self.itemID then
                    return
                end
                BisManager:AddSlotItem(selectedSlotKey, self.itemID)
                if rp.editBox then rp.editBox:SetText("") end
                if rp.searchPanel then rp.searchPanel:Hide() end
                RefreshDetailPanel()
                RefreshSlotList()
            end)
            row:Show()
        elseif row then
            row.itemID = nil
            row:SetScript("OnClick", nil)
            row:Hide()
        end
    end

    if rp.searchEmptyText then
        rp.searchEmptyText:SetShown(visibleRows == 0)
    end
    rp.searchPanel:SetHeight(visibleRows > 0 and (visibleRows * (32 + GAP) + PADDING * 2) or 44)
    rp.searchPanel:Show()
end

------------------------------------------------------------------------
-- Refresh: detail panel
------------------------------------------------------------------------

RefreshDetailPanel = function()
    if not configFrame or not configFrame.rightPanel then return end
    local rp = configFrame.rightPanel

    if not selectedSlotKey then
        rp.headerText:SetText(L["select_slot"])
        SetEquippedItemLine(rp.equippedLine1, nil, nil, nil, nil, "")
        if rp.equippedLine2 then
            SetEquippedItemLine(rp.equippedLine2, nil, nil, nil, nil, "")
            rp.equippedLine2:Hide()
        end
        rp.bisLabel:Hide(); rp.emptyText:Hide(); rp.addSection:Hide()
        if rp.actionsSection then rp.actionsSection:Hide() end
        if rp.searchPanel then rp.searchPanel:Hide() end
        rp.captureBtn:Hide(); rp.clearSlotBtn:Hide()
        for i = 1, MAX_ITEM_ROWS do itemRows[i]:Hide() end
        return
    end

    local slotDef = SLOT_BY_KEY[selectedSlotKey]
    if not slotDef then return end

    rp.headerText:SetText(slotDef.label .. (slotDef.requiredCount and ("  " .. L["required_fmt"]:format(slotDef.requiredCount)) or ""))
    rp.bisLabel:Show(); rp.addSection:Show(); rp.captureBtn:Show(); rp.clearSlotBtn:Show()
    if rp.actionsSection then rp.actionsSection:Show() end
    PreloadSlotSearchItems(slotDef.key)

    -- Equipped item(s)
    if slotDef.subSlots then
        for index, sub in ipairs(slotDef.subSlots) do
            local line = index == 1 and rp.equippedLine1 or rp.equippedLine2
            local eqID = GetInventoryItemID("player", sub.slotID)
            if eqID then
                local isBis = BisManager:HasConfiguredItem(slotDef.key, eqID)
                local prefix = isBis and L["prefix_bis"] or L["prefix_not_bis"]
                local itemLink = GetInventoryItemLink("player", sub.slotID)
                SetEquippedItemLine(line, eqID, itemLink, prefix, BisManager:GetItemText(eqID), L["no_equipped_msg"])
            else
                SetEquippedItemLine(line, nil, nil, nil, nil, L["no_equipped_msg"])
            end
            if line then
                line:Show()
            end
        end
        if rp.equippedLine2 then
            rp.equippedLine2:Show()
        end
    else
        local eqID = slotDef.slotID and GetInventoryItemID("player", slotDef.slotID) or nil
        if eqID then
            local isBis = BisManager:HasConfiguredItem(slotDef.key, eqID)
            local prefix = isBis and L["prefix_bis"] or L["prefix_not_bis"]
            local itemLink = slotDef.slotID and GetInventoryItemLink("player", slotDef.slotID) or nil
            SetEquippedItemLine(rp.equippedLine1, eqID, itemLink, prefix, BisManager:GetItemText(eqID), L["no_equipped_msg"])
        else
            SetEquippedItemLine(rp.equippedLine1, nil, nil, nil, nil, L["no_equipped_msg"])
        end
        if rp.equippedLine1 then
            rp.equippedLine1:Show()
        end
        if rp.equippedLine2 then
            SetEquippedItemLine(rp.equippedLine2, nil, nil, nil, nil, "")
            rp.equippedLine2:Hide()
        end
    end

    -- BiS entries
    local entries = BisManager:GetEntries(slotDef.key)
    local count = entries and #entries or 0
    local profile = BisManager:GetProfile()
    if rp.itemContainer then
        local contentHeight = count > 0 and (count * ITEM_ROW_HEIGHT + math.max(count - 1, 0) * GAP) or 1
        rp.itemContainer:SetHeight(contentHeight)
        if rp.itemScroll and contentHeight <= (rp.itemScroll:GetHeight() or 0) then
            rp.itemScroll:SetVerticalScroll(0)
        end
    end

    local equippedIDs = {}
    if slotDef.subSlots then
        for _, sub in ipairs(slotDef.subSlots) do
            local id = GetInventoryItemID("player", sub.slotID)
            if id then equippedIDs[id] = true end
        end
    else
        local id = slotDef.slotID and GetInventoryItemID("player", slotDef.slotID) or nil
        if id then equippedIDs[id] = true end
    end

    for i = 1, MAX_ITEM_ROWS do
        local row = itemRows[i]
        if i <= count then
            local entry = entries[i]
            row.itemID = entry.itemID
            row.itemLink = BisManager:GetBiSItemLink(entry.itemID)
            row.indexText:SetText(tostring(i) .. ".")
            row.icon:SetTexture(BisManager:GetItemIcon(entry.itemID))
            row.nameText:SetText(row.itemLink or ("item:" .. entry.itemID))
            if equippedIDs[entry.itemID] then
                row.nameText:SetTextColor(0.3, 1, 0.3)
            else
                row.nameText:SetTextColor(1, 1, 1)
            end
            -- Source display
            local sourceData = BisManager:GetDisplayItemSourceData(entry, profile) or {}
            local src = sourceData.label or ""
            if src == "" then
                src = L["source_crafting"]
            end
            local sourceUrl = sourceData.url
            local canOpenJournal = sourceData.journalInstanceID and true or false
            row.sourceDisplayText = src
            row.sourceUrl = sourceUrl
            row.sourceJournalInstanceID = sourceData.journalInstanceID
            row.sourceEncounterID = sourceData.encounterID
            row.sourceItemID = sourceData.itemID
            row.sourceCanOpen = ((sourceUrl and sourceUrl ~= "") or canOpenJournal) and true or false
            if row.sourceCanOpen then
                row.sourceText:SetText("|cff5cc8ff" .. L["source_label"] .. " " .. src .. "|r")
                row.sourceText:SetTextColor(0.36, 0.78, 1)
            else
                row.sourceText:SetText(L["source_label"] .. " " .. src)
                row.sourceText:SetTextColor(0.76, 0.76, 0.58)
            end
            if row.sourceBtnHit and row.sourceText then
                row.sourceBtnHit:SetWidth(math.max(1, math.min(row.sourceText:GetStringWidth() + 6, 300)))
            end
            row.sourceBtnHit:SetScript("OnClick", function()
                if not row.sourceCanOpen then
                    return
                end
                if row.sourceUrl and row.sourceUrl ~= "" then
                    OpenExternalUrl(row.sourceUrl)
                elseif row.sourceJournalInstanceID then
                    BisManager:OpenEncounterJournalSource({
                        journalInstanceID = row.sourceJournalInstanceID,
                        encounterID = row.sourceEncounterID,
                        itemID = row.sourceItemID,
                    })
                end
            end)
            row.sourceBtnHit:EnableMouse(true)
            local ci = i
            row.removeBtn:SetScript("OnClick", function()
                BisManager:RemoveSlotItem(slotDef.key, tostring(ci))
                RefreshDetailPanel(); RefreshSlotList()
            end)
            row:Show()
        else
            row.itemID = nil; row.itemLink = nil; row.sourceUrl = nil; row.sourceDisplayText = nil; row.sourceCanOpen = nil; row.sourceJournalInstanceID = nil; row.sourceEncounterID = nil; row.sourceItemID = nil; row:Hide()
        end
    end
    rp.emptyText:SetShown(count == 0)
end

------------------------------------------------------------------------
-- Refresh: stats panel
------------------------------------------------------------------------

RefreshStatsPanel = function()
    if not configFrame or not configFrame.statsPanel then return end
    local stp = configFrame.statsPanel
    local layout = GetStatsLayout((stp.scrollFrame and stp.scrollFrame:GetWidth() and (stp.scrollFrame:GetWidth() - 12)) or 620)
    stp.statsLayout = layout

    if stp.scrollChild then
        stp.scrollChild:SetWidth(layout.width)
    end
    if stp.colSlot then
        stp.colSlot:SetWidth(layout.slotW)
        stp.colItem:ClearAllPoints()
        stp.colItem:SetPoint("TOPLEFT", stp, "TOPLEFT", 20 + layout.itemX, -42)
        stp.colItem:SetWidth(layout.itemW)
        stp.colCrit:ClearAllPoints()
        stp.colCrit:SetPoint("TOPLEFT", stp, "TOPLEFT", 20 + layout.statX, -42)
        stp.colCrit:SetWidth(layout.statW)
        stp.colHaste:ClearAllPoints()
        stp.colHaste:SetPoint("LEFT", stp.colCrit, "RIGHT", 0, 0)
        stp.colHaste:SetWidth(layout.statW)
        stp.colMastery:ClearAllPoints()
        stp.colMastery:SetPoint("LEFT", stp.colHaste, "RIGHT", 0, 0)
        stp.colMastery:SetWidth(layout.statW)
        stp.colVersa:ClearAllPoints()
        stp.colVersa:SetPoint("LEFT", stp.colMastery, "RIGHT", 0, 0)
        stp.colVersa:SetWidth(layout.statW)
    end

    for _, row in ipairs(statsRows) do row:Hide() end

    local profile = BisManager:GetProfile()
    if not profile or not profile.slots or not next(profile.slots) then
        stp.noDataText:Show()
        if stp.totalRow then stp.totalRow:Hide() end
        return
    end
    stp.noDataText:Hide()

    -- Preload BiS items and schedule a refresh if any are uncached
    local needsRetry = false
    for _, slotDef in ipairs(SLOT_DEFINITIONS) do
        local entries = BisManager:GetEntries(slotDef.key)
        if entries and #entries > 0 then
            local maxEntries = slotDef.subSlots and math.min(#entries, 2) or 1
            for entryIndex = 1, maxEntries do
                local link = BisManager:GetBiSItemLink(entries[entryIndex].itemID)
                if not link then
                    needsRetry = true
                    if C_Item and C_Item.RequestLoadItemDataByID then
                        C_Item.RequestLoadItemDataByID(entries[entryIndex].itemID)
                    end
                end
            end
        end
    end
    if needsRetry then
        C_Timer.After(0.5, function()
            if configFrame and configFrame.statsPanel and configFrame.statsPanel:IsShown() then
                RefreshStatsPanel()
            end
        end)
    end

    local rowIndex = 0
    local grandTotal = { crit = 0, haste = 0, mastery = 0, versatility = 0 }

    for _, slotDef in ipairs(SLOT_DEFINITIONS) do
        local entries = BisManager:GetEntries(slotDef.key)
        if entries and #entries > 0 then
            local maxEntries = slotDef.subSlots and math.min(#entries, 2) or 1
            for entryIndex = 1, maxEntries do
                local entry = entries[entryIndex]
                rowIndex = rowIndex + 1
                if rowIndex > MAX_STATS_ROWS then break end

                local row = statsRows[rowIndex]
                if not row then
                    row = CreateFrame("Frame", nil, stp.scrollChild, BD_TEMPLATE)
                    row:SetSize(layout.width, 22); row:SetPoint("TOPLEFT", 0, -(rowIndex - 1) * 24)
                    row:EnableMouse(true)
                    ApplyBackdrop(row, { 0.095, 0.112, 0.136, 0.72 }, UI.lineSoft, UI.round.row)
                    row.slotText = row:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
                    row.slotText:SetPoint("LEFT", layout.slotX, 0); row.slotText:SetWidth(layout.slotW); row.slotText:SetJustifyH("LEFT")
                    row.icon = row:CreateTexture(nil, "ARTWORK"); row.icon:SetSize(18, 18)
                    row.icon:SetPoint("LEFT", layout.iconX, 0); row.icon:SetTexCoord(0.08, 0.92, 0.08, 0.92)
                    row.nameText = row:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
                    row.nameText:SetPoint("LEFT", layout.itemX, 0); row.nameText:SetWidth(layout.itemW); row.nameText:SetJustifyH("LEFT"); row.nameText:SetWordWrap(false)
                    row.critText = row:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
                    row.critText:SetPoint("LEFT", layout.statX, 0); row.critText:SetWidth(layout.statW); row.critText:SetJustifyH("CENTER")
                    row.hasteText = row:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
                    row.hasteText:SetPoint("LEFT", layout.statX + layout.statW, 0); row.hasteText:SetWidth(layout.statW); row.hasteText:SetJustifyH("CENTER")
                    row.masteryText = row:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
                    row.masteryText:SetPoint("LEFT", layout.statX + layout.statW * 2, 0); row.masteryText:SetWidth(layout.statW); row.masteryText:SetJustifyH("CENTER")
                    row.versaText = row:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
                    row.versaText:SetPoint("LEFT", layout.statX + layout.statW * 3, 0); row.versaText:SetWidth(layout.statW); row.versaText:SetJustifyH("CENTER")
                    row.bg = row:CreateTexture(nil, "BACKGROUND")
                    row.bg:SetPoint("TOPLEFT", 5, -3)
                    row.bg:SetPoint("BOTTOMRIGHT", -5, 3)
                    row.bg:SetColorTexture((rowIndex % 2 == 0) and 0.07 or 0.045, (rowIndex % 2 == 0) and 0.08 or 0.055, (rowIndex % 2 == 0) and 0.095 or 0.07, 0.38)
                    row:SetScript("OnEnter", function(self)
                        if not self.itemLink then
                            return
                        end
                        GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
                        GameTooltip:SetHyperlink(self.itemLink)
                        GameTooltip:Show()
                    end)
                    row:SetScript("OnLeave", GameTooltip_Hide)
                    statsRows[rowIndex] = row
                end
                row:SetWidth(layout.width)
                row.slotText:SetWidth(layout.slotW)
                row.icon:ClearAllPoints()
                row.icon:SetPoint("LEFT", layout.iconX, 0)
                row.nameText:ClearAllPoints()
                row.nameText:SetPoint("LEFT", layout.itemX, 0)
                row.nameText:SetWidth(layout.itemW)
                row.critText:ClearAllPoints()
                row.critText:SetPoint("LEFT", layout.statX, 0)
                row.critText:SetWidth(layout.statW)
                row.hasteText:ClearAllPoints()
                row.hasteText:SetPoint("LEFT", layout.statX + layout.statW, 0)
                row.hasteText:SetWidth(layout.statW)
                row.masteryText:ClearAllPoints()
                row.masteryText:SetPoint("LEFT", layout.statX + layout.statW * 2, 0)
                row.masteryText:SetWidth(layout.statW)
                row.versaText:ClearAllPoints()
                row.versaText:SetPoint("LEFT", layout.statX + layout.statW * 3, 0)
                row.versaText:SetWidth(layout.statW)

                row.slotText:SetText(GetStatsSlotLabel(slotDef, entryIndex))
                row.icon:SetTexture(BisManager:GetItemIcon(entry.itemID))
                local itemLink = BisManager:GetBiSItemLink(entry.itemID)
                row.itemLink = itemLink
                row.nameText:SetText(itemLink or ("|cff999999item:" .. entry.itemID .. "|r"))

                -- Get secondary stats
                local crit, haste, mastery, versa = 0, 0, 0, 0
                if itemLink then
                    local itemStats
                    if C_Item and C_Item.GetItemStats then
                        itemStats = C_Item.GetItemStats(itemLink)
                    elseif GetItemStats then
                        itemStats = GetItemStats(itemLink)
                    end
                    if itemStats then
                        crit = itemStats["ITEM_MOD_CRIT_RATING_SHORT"] or 0
                        haste = itemStats["ITEM_MOD_HASTE_RATING_SHORT"] or 0
                        mastery = itemStats["ITEM_MOD_MASTERY_RATING_SHORT"] or 0
                        versa = itemStats["ITEM_MOD_VERSATILITY"] or 0
                    end
                end
                local itemSecTotal = crit + haste + mastery + versa

                grandTotal.crit = grandTotal.crit + crit
                grandTotal.haste = grandTotal.haste + haste
                grandTotal.mastery = grandTotal.mastery + mastery
                grandTotal.versatility = grandTotal.versatility + versa

                local function FmtStat(val, total)
                    if val == 0 then return "|cff666666-|r" end
                    local pct = total > 0 and (val / total * 100) or 0
                    return ("|cffffffff%d|r |cffaaaaaa(%.0f%%)|r"):format(val, pct)
                end

                row.critText:SetText(FmtStat(crit, itemSecTotal))
                row.hasteText:SetText(FmtStat(haste, itemSecTotal))
                row.masteryText:SetText(FmtStat(mastery, itemSecTotal))
                row.versaText:SetText(FmtStat(versa, itemSecTotal))
                row:Show()
            end
        end
        if rowIndex > MAX_STATS_ROWS then break end
    end

    stp.scrollChild:SetHeight(math.max(rowIndex * 24 + 4, 10))

    -- Total row
    if not stp.totalRow then
        stp.totalRow = CreateFrame("Frame", nil, stp, BD_TEMPLATE)
        stp.totalRow:SetSize(layout.width, 26)
        ApplyBackdrop(stp.totalRow, { 0.070, 0.150, 0.210, 0.80 }, UI.lineStrong, UI.round.row)
        stp.totalRow.bg = stp.totalRow:CreateTexture(nil, "BACKGROUND")
        stp.totalRow.bg:SetPoint("TOPLEFT", 5, -4)
        stp.totalRow.bg:SetPoint("BOTTOMRIGHT", -5, 4)
        stp.totalRow.bg:SetColorTexture(0.36, 0.78, 1, 0.08)
        stp.totalRow.label = stp.totalRow:CreateFontString(nil, "OVERLAY", "GameFontNormal")
        stp.totalRow.label:SetPoint("LEFT", layout.slotX, 0); stp.totalRow.label:SetWidth(layout.statX - layout.slotX); stp.totalRow.label:SetJustifyH("LEFT")
        stp.totalRow.critText = stp.totalRow:CreateFontString(nil, "OVERLAY", "GameFontNormal")
        stp.totalRow.critText:SetPoint("LEFT", layout.statX, 0); stp.totalRow.critText:SetWidth(layout.statW); stp.totalRow.critText:SetJustifyH("CENTER")
        stp.totalRow.hasteText = stp.totalRow:CreateFontString(nil, "OVERLAY", "GameFontNormal")
        stp.totalRow.hasteText:SetPoint("LEFT", layout.statX + layout.statW, 0); stp.totalRow.hasteText:SetWidth(layout.statW); stp.totalRow.hasteText:SetJustifyH("CENTER")
        stp.totalRow.masteryText = stp.totalRow:CreateFontString(nil, "OVERLAY", "GameFontNormal")
        stp.totalRow.masteryText:SetPoint("LEFT", layout.statX + layout.statW * 2, 0); stp.totalRow.masteryText:SetWidth(layout.statW); stp.totalRow.masteryText:SetJustifyH("CENTER")
        stp.totalRow.versaText = stp.totalRow:CreateFontString(nil, "OVERLAY", "GameFontNormal")
        stp.totalRow.versaText:SetPoint("LEFT", layout.statX + layout.statW * 3, 0); stp.totalRow.versaText:SetWidth(layout.statW); stp.totalRow.versaText:SetJustifyH("CENTER")
    end
    stp.totalRow:SetWidth(layout.width)
    stp.totalRow.label:SetWidth(layout.statX - layout.slotX)
    stp.totalRow.critText:SetWidth(layout.statW)
    stp.totalRow.hasteText:SetWidth(layout.statW)
    stp.totalRow.masteryText:SetWidth(layout.statW)
    stp.totalRow.versaText:SetWidth(layout.statW)
    stp.totalRow.critText:ClearAllPoints()
    stp.totalRow.critText:SetPoint("LEFT", layout.statX, 0)
    stp.totalRow.hasteText:ClearAllPoints()
    stp.totalRow.hasteText:SetPoint("LEFT", layout.statX + layout.statW, 0)
    stp.totalRow.masteryText:ClearAllPoints()
    stp.totalRow.masteryText:SetPoint("LEFT", layout.statX + layout.statW * 2, 0)
    stp.totalRow.versaText:ClearAllPoints()
    stp.totalRow.versaText:SetPoint("LEFT", layout.statX + layout.statW * 3, 0)
    stp.totalRow:SetPoint("BOTTOMLEFT", 20, 16)
    stp.totalRow.label:SetText(L["stats_total"])
    stp.totalRow.label:SetTextColor(1, 0.82, 0)

    local gt = grandTotal.crit + grandTotal.haste + grandTotal.mastery + grandTotal.versatility
    local function FmtTotal(val)
        if val == 0 and gt == 0 then return "-" end
        local pct = gt > 0 and (val / gt * 100) or 0
        return ("|cffffffff%d|r |cff5cc8ff(%.1f%%)|r"):format(val, pct)
    end
    stp.totalRow.critText:SetText(FmtTotal(grandTotal.crit))
    stp.totalRow.hasteText:SetText(FmtTotal(grandTotal.haste))
    stp.totalRow.masteryText:SetText(FmtTotal(grandTotal.mastery))
    stp.totalRow.versaText:SetText(FmtTotal(grandTotal.versatility))
    stp.totalRow:Show()
end

------------------------------------------------------------------------
-- Refresh: settings
------------------------------------------------------------------------

RefreshSettingsPanel = function()
    if not configFrame or not configFrame.settingsPanel or not BisManager.db then return end
    local sp = configFrame.settingsPanel
    sp.enabledCheck:SetChecked(BisManager.db.display.enabled)
    sp.showIlvlCheck:SetChecked(BisManager.db.display.showIlvl)
    sp.scaleSlider.slider:SetValue(BisManager.db.display.scale)
    sp.scaleSlider.valueText:SetText(("%.2f"):format(BisManager.db.display.scale))
    sp.alphaSlider.slider:SetValue(BisManager.db.display.alpha)
    sp.alphaSlider.valueText:SetText(("%.2f"):format(BisManager.db.display.alpha))
end

------------------------------------------------------------------------
-- Refresh: import/export panel
------------------------------------------------------------------------

RefreshImportPanel = function()
    if not configFrame or not configFrame.importPanel then return end
    local ip = configFrame.importPanel
    if ip.profileEditBox and not ip.profileEditBox:HasFocus() then
        ip.profileEditBox:SetText(BisManager:GetActiveProfileName())
    end
end

------------------------------------------------------------------------
-- Refresh: profiles panel
------------------------------------------------------------------------

RefreshProfilesPanel = function()
    if not configFrame or not configFrame.profilesPanel then return end
    local pp = configFrame.profilesPanel

    -- Split profiles into generated vs user
    local generatedNames = {}
    local userNames = {}
    local allNames = BisManager:GetProfileNames()
    local activeName = BisManager:GetActiveProfileName()

    for _, name in ipairs(allNames) do
        if BisManager:IsAutoProfile(name) then
            generatedNames[#generatedNames + 1] = name
        else
            userNames[#userNames + 1] = name
        end
    end

    -- Update generated header with spec info
    if pp.genHeader then
        local specID, classKey, specKey = BisManager:GetPlayerSpecInfo()
        if specID then
            pp.genHeader:SetText(L["profile_section_generated"])
            if pp.generatedSummary then
                pp.generatedSummary:SetText(L["profile_spec_summary"]:format(specID, classKey or "?", specKey or "?"))
            end
        else
            pp.genHeader:SetText(L["profile_section_generated"])
            if pp.generatedSummary then
                pp.generatedSummary:SetText("|cffff6666" .. L["profile_no_spec_detected"] .. "|r")
            end
        end
    end

    -- Update generated profile list
    if pp.generatedListContainer then
        local MAX_GEN = pp.maxGeneratedRows or 8
        if pp.generatedContent then
            pp.generatedContent:SetHeight(math.max(math.min(#generatedNames, MAX_GEN), 1) * (36 + GAP))
        end
        for i = 1, MAX_GEN do
            local btn = pp.generatedButtons[i]
            if btn then
                if i <= #generatedNames then
                    local name = generatedNames[i]
                    local isActive = (name == activeName)
                    local provider, mode = SplitGeneratedProfileName(name)
                    btn.text:SetText(provider)
                    btn.metaText:SetText((mode ~= "" and mode or name) .. (isActive and ("  " .. L["profile_active_marker"]) or ""))
                    btn.metaText:SetTextColor(isActive and UI.twEmeraldHover[1] or 0.56, isActive and UI.twEmeraldHover[2] or 0.68, isActive and UI.twEmeraldHover[3] or 0.78)
                    btn:SetScript("OnClick", function(self, clickedButton)
                        if clickedButton == "RightButton" then
                            if self.url and self.url ~= "" then
                                OpenExternalUrl(self.url)
                            end
                            return
                        end
                        BisManager:SetActiveProfile(name)
                        RefreshProfilesPanel()
                        if RefreshSlotList then RefreshSlotList() end
                        if RefreshDetailPanel then RefreshDetailPanel() end
                    end)
                    btn:SetScript("OnEnter", function(self)
                        GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
                        GameTooltip:AddLine(provider, 1, 1, 1, true)
                        if mode and mode ~= "" then
                            GameTooltip:AddLine(mode, 0.56, 0.68, 0.78, true)
                        end
                        GameTooltip:AddLine(" ")
                        GameTooltip:AddLine(L["profile_tooltip_left_activate"], 0.36, 0.78, 1, true)
                        if self.url and self.url ~= "" then
                            GameTooltip:AddLine(L["profile_tooltip_right_open_link"], 0.36, 0.78, 1, true)
                            GameTooltip:AddLine(" ")
                            GameTooltip:AddLine(L["profile_tooltip_link"], 0.8, 0.8, 0.8, true)
                            GameTooltip:AddLine(self.url, 0.36, 0.78, 1, true)
                        end
                        GameTooltip:Show()
                    end)
                    btn:SetScript("OnLeave", GameTooltip_Hide)
                    btn:Show()
                    -- Source URL display
                    if btn.urlText then
                        local profile = BisManager:GetProfile(name)
                        local url = profile and profile.sourceUrl
                        btn.urlText:SetText("")
                        btn.url = url
                        if url and url ~= "" then
                            btn.urlText:Hide()
                            if btn.urlBtn then btn.urlBtn:Hide() end
                        else
                            btn.urlText:Hide()
                            if btn.urlBtn then btn.urlBtn:Hide() end
                        end
                    end
                else
                    btn:Hide()
                    if btn.metaText then btn.metaText:SetText("") end
                    btn:SetScript("OnEnter", nil)
                    btn:SetScript("OnLeave", nil)
                    btn:SetScript("OnClick", nil)
                    if btn.urlBtn then btn.urlBtn:Hide() end
                end
            end
        end
        pp.generatedEmptyText:SetShown(#generatedNames == 0)
    end

    -- Update user profile list
    if pp.userListContainer then
        local MAX_USR = pp.maxUserRows or 8
        for i = 1, MAX_USR do
            local btn = pp.userButtons[i]
            if btn then
                if i <= #userNames then
                    local name = userNames[i]
                    local isActive = (name == activeName)
                    btn.text:SetText(name .. (isActive and (L["profile_active_marker"]) or ""))
                    btn:SetScript("OnClick", function()
                        BisManager:SetActiveProfile(name)
                        RefreshProfilesPanel()
                        if RefreshSlotList then RefreshSlotList() end
                        if RefreshDetailPanel then RefreshDetailPanel() end
                    end)
                    btn:SetScript("OnEnter", function(self)
                        GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
                        GameTooltip:AddLine(name, 1, 1, 1, true)
                        GameTooltip:AddLine(" ")
                        GameTooltip:AddLine(L["profile_tooltip_left_activate"], 0.36, 0.78, 1, true)
                        GameTooltip:Show()
                    end)
                    btn:SetScript("OnLeave", GameTooltip_Hide)
                    btn:Show()
                    if btn.delBtn then
                        btn.delBtn:SetScript("OnClick", function()
                            BisManager:DeleteProfile(name)
                            RefreshProfilesPanel()
                            if RefreshSlotList then RefreshSlotList() end
                            if RefreshDetailPanel then RefreshDetailPanel() end
                        end)
                        btn.delBtn:Show()
                    end
                else
                    btn:Hide()
                    btn:SetScript("OnEnter", nil)
                    btn:SetScript("OnLeave", nil)
                    btn:SetScript("OnClick", nil)
                    if btn.delBtn then btn.delBtn:Hide() end
                end
            end
        end
        pp.userEmptyText:SetShown(#userNames == 0)
    end
end

------------------------------------------------------------------------
-- Tab switching (5 tabs)
------------------------------------------------------------------------

SwitchTab = function(tabKey)
    if not configFrame then return end
    local tabs = { slots = false, stats = false, profiles = false, import = false, settings = false }
    tabs[tabKey] = true

    configFrame.slotsPanel:SetShown(tabs.slots)
    configFrame.statsPanel:SetShown(tabs.stats)
    configFrame.settingsPanel:SetShown(tabs.settings)
    if configFrame.importPanel then configFrame.importPanel:SetShown(tabs.import) end
    if configFrame.profilesPanel then configFrame.profilesPanel:SetShown(tabs.profiles) end

    for key, tab in pairs(configFrame.tabs) do
        if tab.SetBackdropColor then
            local active = (key == tabKey)
            if active then
                tab:SetBackdropColor(unpack(UI.twSky))
                tab:SetBackdropBorderColor(UI.blue[1], UI.blue[2], UI.blue[3], 0.95)
                if tab.text then tab.text:SetTextColor(0.93, 0.98, 1) end
            else
                tab:SetBackdropColor(0, 0, 0, 0)
                tab:SetBackdropBorderColor(0, 0, 0, 0)
                if tab.text then tab.text:SetTextColor(0.80, 0.86, 0.92) end
            end
        end
    end

    if configFrame.profileText and BisManager.GetActiveProfileName then
        configFrame.profileText:SetText(L["profile_select"] .. " " .. BisManager:GetActiveProfileName())
    end

    if tabs.slots then RefreshSlotList(); RefreshDetailPanel()
    elseif tabs.stats then RefreshStatsPanel()
    elseif tabs.profiles then RefreshProfilesPanel()
    elseif tabs.import then RefreshImportPanel()
    elseif tabs.settings then RefreshSettingsPanel() end
end

------------------------------------------------------------------------
-- Main frame creation
------------------------------------------------------------------------

CreateConfigFrame = function()
    if configFrame then return configFrame end

    configFrame = CreateFrame("Frame", "BisManagerConfigFrame", UIParent, BD_TEMPLATE)
    configFrame:SetSize(960, 700); configFrame:SetPoint("CENTER")
    configFrame:SetMovable(true); configFrame:EnableMouse(true); configFrame:SetClampedToScreen(true)
    configFrame:RegisterForDrag("LeftButton")
    configFrame:SetScript("OnDragStart", configFrame.StartMoving)
    configFrame:SetScript("OnDragStop", configFrame.StopMovingOrSizing)
    configFrame:SetFrameStrata("DIALOG"); configFrame:SetFrameLevel(100)
    ApplyBackdrop(configFrame, UI.bg, UI.lineStrong, UI.round.frame)
    tinsert(UISpecialFrames, "BisManagerConfigFrame")

    configFrame.header = CreateFrame("Frame", nil, configFrame, BD_TEMPLATE)
    configFrame.header:SetPoint("TOPLEFT", PADDING, -PADDING)
    configFrame.header:SetPoint("TOPRIGHT", -PADDING, -PADDING)
    configFrame.header:SetHeight(64)
    ApplyBackdrop(configFrame.header, UI.header, UI.line, UI.round.card)

    configFrame.icon = configFrame.header:CreateTexture(nil, "ARTWORK")
    configFrame.icon:SetSize(30, 30)
    configFrame.icon:SetPoint("LEFT", PADDING, 4)
    configFrame.icon:SetTexture(BisManager.ADDON_ICON or DEFAULT_ICON)

    configFrame.titleText = configFrame.header:CreateFontString(nil, "OVERLAY", "GameFontNormalLarge")
    configFrame.titleText:SetPoint("LEFT", configFrame.icon, "RIGHT", GAP, 10)
    configFrame.titleText:SetText(L["config_title"])
    configFrame.titleText:SetTextColor(0.94, 0.98, 1)

    configFrame.profileText = configFrame.header:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
    configFrame.profileText:SetPoint("TOPLEFT", configFrame.titleText, "BOTTOMLEFT", 0, -3)
    configFrame.profileText:SetTextColor(0.58, 0.66, 0.74)
    configFrame.profileText:SetText("")

    local closeBtn = CreateFrame("Button", nil, configFrame.header, BD_TEMPLATE)
    closeBtn:SetSize(28, 28)
    closeBtn:SetPoint("RIGHT", configFrame.header, "RIGHT", -PADDING, 2)
    closeBtn.text = closeBtn:CreateFontString(nil, "OVERLAY", "GameFontNormal")
    closeBtn.text:SetAllPoints()
    closeBtn.text:SetText("X")
    SkinButton(closeBtn, "danger")
    closeBtn:SetScript("OnClick", function()
        configFrame:Hide()
    end)

    -- Tabs (5)
    configFrame.tabs = {}
    configFrame.tabBar = CreateFrame("Frame", nil, configFrame.header, BD_TEMPLATE)
    configFrame.tabBar:SetSize(560, 36)
    configFrame.tabBar:SetPoint("LEFT", configFrame.header, "LEFT", 330, 2)
    ApplyBackdrop(configFrame.tabBar, { 0.042, 0.052, 0.066, 0.82 }, UI.line, UI.round.pill)

    local function MakeTab(label, tabKey)
        local tab = CreateFrame("Button", nil, configFrame.tabBar, BD_TEMPLATE); tab:SetSize(96, 28)
        ApplyBackdrop(tab, { 0, 0, 0, 0 }, { 0, 0, 0, 0 }, UI.round.pill)
        tab.text = tab:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall"); tab.text:SetAllPoints(); tab.text:SetText(label)
        tab.text:SetTextColor(0.80, 0.86, 0.92)
        tab.hl = tab:CreateTexture(nil, "HIGHLIGHT")
        tab.hl:SetPoint("TOPLEFT", 5, -4)
        tab.hl:SetPoint("BOTTOMRIGHT", -5, 4)
        tab.hl:SetColorTexture(UI.twSkyHover[1], UI.twSkyHover[2], UI.twSkyHover[3], 0.28)
        tab:SetScript("OnClick", function() SwitchTab(tabKey) end)
        configFrame.tabs[tabKey] = tab
        return tab
    end
    local tabSlots = MakeTab(L["tab_slots"], "slots"); tabSlots:SetPoint("LEFT", configFrame.tabBar, "LEFT", RADIUS, 0)
    local tabStats = MakeTab(L["tab_stats"], "stats"); tabStats:SetPoint("LEFT", tabSlots, "RIGHT", GAP, 0)
    local tabProfiles = MakeTab(L["tab_profiles"], "profiles"); tabProfiles:SetPoint("LEFT", tabStats, "RIGHT", GAP, 0)
    local tabImport = MakeTab(L["tab_import_export"], "import"); tabImport:SetSize(128, 28); tabImport:SetPoint("LEFT", tabProfiles, "RIGHT", GAP, 0)
    local tabSettings = MakeTab(L["tab_settings"], "settings"); tabSettings:SetPoint("LEFT", tabImport, "RIGHT", GAP, 0)

    local sep = configFrame:CreateTexture(nil, "ARTWORK"); sep:SetColorTexture(0, 0, 0, 0); sep:SetHeight(1)
    sep:SetPoint("TOPLEFT", PADDING, -80); sep:SetPoint("TOPRIGHT", -PADDING, -80)

    ----------------------------------------------------------------
    -- TAB 1: SLOTS PANEL
    ----------------------------------------------------------------
    configFrame.slotsPanel = CreateFrame("Frame", nil, configFrame)
    configFrame.slotsPanel:SetPoint("TOPLEFT", PADDING, -80); configFrame.slotsPanel:SetPoint("BOTTOMRIGHT", -PADDING, PADDING)

    local leftPanel = CreateBentoCard(configFrame.slotsPanel, L["tab_slots"], UI.gold)
    leftPanel:SetPoint("TOPLEFT")
    leftPanel:SetPoint("BOTTOMLEFT", 0, 54)
    leftPanel:SetWidth(270)

    configFrame.ilvlHeader = leftPanel:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    configFrame.ilvlHeader:SetPoint("TOPRIGHT", leftPanel, "TOPRIGHT", -14, -12); configFrame.ilvlHeader:SetTextColor(1, 0.82, 0); configFrame.ilvlHeader:SetText("")
    configFrame.ilvlHeader:Hide()

    local scrollFrame = CreateFrame("ScrollFrame", "BisManagerSlotScroll", leftPanel, "UIPanelScrollFrameTemplate")
    scrollFrame:SetPoint("TOPLEFT", PADDING, -32); scrollFrame:SetPoint("BOTTOMRIGHT", -24, PADDING)
    SkinScrollFrame(scrollFrame)
    local scrollChild = CreateFrame("Frame", nil, scrollFrame)
    scrollChild:SetSize(222, #SLOT_DEFINITIONS * (38 + GAP) + PADDING); scrollFrame:SetScrollChild(scrollChild)
    for i, sd in ipairs(SLOT_DEFINITIONS) do
        slotButtons[sd.key] = CreateSlotButton(scrollChild, i, sd)
    end

    -- Right panel (detail)
    local rightPanel = CreateBentoCard(configFrame.slotsPanel, nil, UI.blue)
    rightPanel:SetPoint("TOPLEFT", leftPanel, "TOPRIGHT", GAP, 0)
    rightPanel:SetPoint("BOTTOMRIGHT", 0, 54)
    configFrame.rightPanel = rightPanel

    rightPanel.headerText = rightPanel:CreateFontString(nil, "OVERLAY", "GameFontNormalLarge")
    rightPanel.headerText:SetPoint("TOPLEFT", PADDING, -PADDING); rightPanel.headerText:SetText(L["select_slot"]); rightPanel.headerText:SetTextColor(UI.blue[1], UI.blue[2], UI.blue[3])

    rightPanel.equippedLine1 = CreateEquippedItemLine(rightPanel, -34)
    rightPanel.equippedLine2 = CreateEquippedItemLine(rightPanel, -52)
    rightPanel.equippedLine2:Hide()

    rightPanel.bisLabel = rightPanel:CreateFontString(nil, "OVERLAY", "GameFontNormal")
    rightPanel.bisLabel:SetPoint("TOPLEFT", PADDING, -78); rightPanel.bisLabel:SetText(L["bis_configured"])
    rightPanel.bisLabel:SetTextColor(1, 0.82, 0); rightPanel.bisLabel:Hide()

    rightPanel.itemScroll = CreateFrame("ScrollFrame", "BisManagerDetailItemScroll", rightPanel, "UIPanelScrollFrameTemplate")
    rightPanel.itemScroll:SetPoint("TOPLEFT", PADDING, -104)
    rightPanel.itemScroll:SetPoint("BOTTOMRIGHT", -24, 154)
    SkinScrollFrame(rightPanel.itemScroll)

    rightPanel.itemContainer = CreateFrame("Frame", nil, rightPanel.itemScroll)
    rightPanel.itemContainer:SetSize(390, 1)
    rightPanel.itemScroll:SetScript("OnSizeChanged", function(self, width)
        rightPanel.itemContainer:SetWidth(math.max(1, width - 4))
    end)
    rightPanel.itemScroll:SetScrollChild(rightPanel.itemContainer)
    for i = 1, MAX_ITEM_ROWS do
        itemRows[i] = CreateItemRow(rightPanel.itemContainer, i)
    end

    rightPanel.emptyText = rightPanel:CreateFontString(nil, "OVERLAY", "GameFontDisable")
    rightPanel.emptyText:SetPoint("TOPLEFT", rightPanel.itemScroll, "TOPLEFT", 22, -6)
    rightPanel.emptyText:SetText(L["no_bis_slot"]); rightPanel.emptyText:Hide()

    -- Search/add item section
    rightPanel.addSection = CreateFrame("Frame", nil, rightPanel, BD_TEMPLATE)
    rightPanel.addSection:SetPoint("BOTTOMLEFT", PADDING, 84)
    rightPanel.addSection:SetPoint("BOTTOMRIGHT", -PADDING, 84)
    rightPanel.addSection:SetHeight(68); rightPanel.addSection:Hide()
    ApplyBackdrop(rightPanel.addSection, UI.panelAlt, UI.lineSoft, UI.round.card)

    local addLabel = rightPanel.addSection:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    addLabel:SetPoint("TOPLEFT", PADDING, -PADDING); addLabel:SetText(L["search_by_name"]); addLabel:SetTextColor(0.74, 0.80, 0.86)

    rightPanel.editBox = CreateFrame("EditBox", "BisManagerAddItemEditBox", rightPanel.addSection, EDITBOX_TEMPLATE)
    rightPanel.editBox:SetPoint("TOPLEFT", PADDING, -34)
    rightPanel.editBox:SetPoint("RIGHT", -100, 0)
    rightPanel.editBox:SetHeight(22)
    rightPanel.editBox:SetAutoFocus(false); rightPanel.editBox:SetMaxLetters(256); rightPanel.editBox:SetFontObject("ChatFontNormal")
    SkinEditBox(rightPanel.editBox)

    local addBtn = WarningBtn(rightPanel.addSection, L["btn_add"], 86, 28)
    addBtn:SetPoint("RIGHT", -PADDING, -11)

    rightPanel.searchPanel = CreateFrame("Frame", nil, rightPanel, BD_TEMPLATE)
    rightPanel.searchPanel:SetPoint("BOTTOMLEFT", rightPanel.addSection, "TOPLEFT", 0, GAP)
    rightPanel.searchPanel:SetPoint("BOTTOMRIGHT", rightPanel.addSection, "TOPRIGHT", 0, GAP)
    rightPanel.searchPanel:SetHeight(44)
    ApplyBackdrop(rightPanel.searchPanel, UI.panelAlt, UI.lineSoft, UI.round.card)
    rightPanel.searchPanel:Hide()
    rightPanel.searchRows = {}

    rightPanel.searchEmptyText = rightPanel.searchPanel:CreateFontString(nil, "OVERLAY", "GameFontDisable")
    rightPanel.searchEmptyText:SetPoint("CENTER")
    rightPanel.searchEmptyText:SetText(L["search_no_result"])
    rightPanel.searchEmptyText:Hide()

    for i = 1, MAX_SEARCH_ROWS do
        local row = CreateFrame("Button", nil, rightPanel.searchPanel, BD_TEMPLATE)
        row:SetPoint("TOPLEFT", PADDING, -PADDING - (i - 1) * (32 + GAP))
        row:SetPoint("RIGHT", -PADDING, 0)
        row:SetHeight(32)
        ApplyBackdrop(row, { 0.105, 0.125, 0.154, 0.86 }, UI.lineSoft, UI.round.row)
        row.bg = row:CreateTexture(nil, "BACKGROUND")
        row.bg:SetPoint("TOPLEFT", 5, -4)
        row.bg:SetPoint("BOTTOMRIGHT", -5, 4)
        row.bg:SetColorTexture(0.07, 0.085, 0.105, 0.38)
        row.hl = row:CreateTexture(nil, "HIGHLIGHT")
        row.hl:SetPoint("TOPLEFT", 5, -4)
        row.hl:SetPoint("BOTTOMRIGHT", -5, 4)
        row.hl:SetColorTexture(0.36, 0.78, 1, 0.18)
        row.icon = row:CreateTexture(nil, "ARTWORK")
        row.icon:SetSize(24, 24)
        row.icon:SetPoint("LEFT", 6, 0)
        row.icon:SetTexCoord(0.08, 0.92, 0.08, 0.92)
        row.text = row:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
        row.text:SetPoint("LEFT", row.icon, "RIGHT", 8, 5)
        row.text:SetPoint("RIGHT", -90, 0)
        row.text:SetJustifyH("LEFT")
        row.text:SetWordWrap(false)
        row.meta = row:CreateFontString(nil, "OVERLAY", "GameFontDisableSmall")
        row.meta:SetPoint("LEFT", row.icon, "RIGHT", 8, -8)
        row.meta:SetPoint("RIGHT", -90, 0)
        row.meta:SetJustifyH("LEFT")
        row.meta:SetWordWrap(false)
        row.addText = row:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
        row.addText:SetPoint("RIGHT", -8, 0)
        row.addText:SetText(L["btn_add"])
        row.addText:SetTextColor(UI.gold[1], UI.gold[2], UI.gold[3])
        row:Hide()
        rightPanel.searchRows[i] = row
    end

    local function DoAddItem()
        if not selectedSlotKey then return end
        local text = rightPanel.editBox:GetText()
        if not text or text:match("^%s*$") then return end
        local itemID = BisManager:ResolveItemID(text)
        if itemID then
            BisManager:AddSlotItem(selectedSlotKey, itemID)
            rightPanel.editBox:SetText(""); RefreshDetailPanel(); RefreshSlotList()
        else
            local results = GetSlotSearchResults(selectedSlotKey, text, 1)
            if results[1] and results[1].itemID then
                BisManager:AddSlotItem(selectedSlotKey, results[1].itemID)
                rightPanel.editBox:SetText("")
                if rightPanel.searchPanel then rightPanel.searchPanel:Hide() end
                RefreshDetailPanel(); RefreshSlotList()
                return
            end
            -- Try search by name via GetItemInfo
            local _, link = GetItemInfo(text)
            if link then
                local id = tonumber(link:match("item:(%d+)"))
                if id then
                    BisManager:AddSlotItem(selectedSlotKey, id)
                    rightPanel.editBox:SetText(""); RefreshDetailPanel(); RefreshSlotList()
                    return
                end
            end
            rightPanel.editBox:HighlightText()
        end
    end
    addBtn:SetScript("OnClick", DoAddItem)
    rightPanel.editBox:SetScript("OnTextChanged", function()
        RefreshSlotSearchResults()
        if C_Timer and not rightPanel.searchRetryScheduled then
            rightPanel.searchRetryScheduled = true
            C_Timer.After(0.6, function()
                rightPanel.searchRetryScheduled = nil
                RefreshSlotSearchResults()
            end)
        end
    end)
    rightPanel.editBox:SetScript("OnEnterPressed", function(self) DoAddItem(); self:ClearFocus() end)
    rightPanel.editBox:SetScript("OnEscapePressed", function(self)
        self:SetText("")
        self:ClearFocus()
        if rightPanel.searchPanel then rightPanel.searchPanel:Hide() end
    end)

    local origInsertLink = ChatEdit_InsertLink
    ChatEdit_InsertLink = function(text, ...)
        if BisManagerConfigFrame and BisManagerConfigFrame:IsShown() and rightPanel.editBox:IsVisible() then
            rightPanel.editBox:SetText(text); rightPanel.editBox:SetFocus(); return true
        end
        if origInsertLink then return origInsertLink(text, ...) end
    end

    rightPanel.actionsSection = CreateFrame("Frame", nil, rightPanel, BD_TEMPLATE)
    rightPanel.actionsSection:SetPoint("BOTTOMLEFT", PADDING, PADDING)
    rightPanel.actionsSection:SetPoint("BOTTOMRIGHT", -PADDING, PADDING)
    rightPanel.actionsSection:SetHeight(58)
    ApplyBackdrop(rightPanel.actionsSection, UI.panelAlt, UI.lineSoft, UI.round.card)
    rightPanel.actionsSection:Hide()

    local actionsLabel = rightPanel.actionsSection:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    actionsLabel:SetPoint("TOPLEFT", PADDING, -PADDING)
    actionsLabel:SetText(L["actions_header"])
    actionsLabel:SetTextColor(0.74, 0.80, 0.86)

    rightPanel.captureBtn = SuccessBtn(rightPanel.actionsSection, L["btn_capture"], 150, 28)
    rightPanel.captureBtn:SetPoint("BOTTOMLEFT", PADDING, PADDING)
    rightPanel.captureBtn:SetScript("OnClick", function()
        if not selectedSlotKey then return end
        local sd = SLOT_BY_KEY[selectedSlotKey]
        if sd and BisManager:CaptureSlot(sd) then RefreshDetailPanel(); RefreshSlotList() end
    end)
    rightPanel.captureBtn:Hide()

    rightPanel.clearSlotBtn = DangerBtn(rightPanel.actionsSection, L["btn_clear_slot"], 140, 28)
    rightPanel.clearSlotBtn:SetPoint("LEFT", rightPanel.captureBtn, "RIGHT", GAP, 0)
    rightPanel.clearSlotBtn:SetScript("OnClick", function()
        if not selectedSlotKey then return end
        BisManager:ClearSlot(selectedSlotKey); RefreshDetailPanel(); RefreshSlotList()
    end)
    rightPanel.clearSlotBtn:Hide()

    -- Profile dropdown at bottom of slots panel
    local profileCard = CreateBentoCard(configFrame.slotsPanel, nil, UI.blue)
    profileCard:SetPoint("BOTTOMLEFT", 0, 0)
    profileCard:SetPoint("BOTTOMRIGHT", 0, 0)
    profileCard:SetHeight(46)
    configFrame.profileDropdown = CreateProfileDropdown(profileCard)
    configFrame.profileDropdown:SetPoint("LEFT", PADDING, 0)

    ----------------------------------------------------------------
    -- TAB 2: STATS PANEL
    ----------------------------------------------------------------
    configFrame.statsPanel = CreateFrame("Frame", nil, configFrame, BD_TEMPLATE)
    configFrame.statsPanel:SetPoint("TOPLEFT", PADDING, -80); configFrame.statsPanel:SetPoint("BOTTOMRIGHT", -PADDING, PADDING)
    SkinPanel(configFrame.statsPanel)
    configFrame.statsPanel:Hide()
    local stp = configFrame.statsPanel

    local stHeader = stp:CreateFontString(nil, "OVERLAY", "GameFontNormalLarge")
    stHeader:SetPoint("TOPLEFT", 20, -16); stHeader:SetText(L["stats_header"]); stHeader:SetTextColor(UI.blue[1], UI.blue[2], UI.blue[3])

    stp.statsLayout = GetStatsLayout(620)
    local colY = -42
    local colSlot = stp:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    colSlot:SetPoint("TOPLEFT", 24, colY); colSlot:SetWidth(stp.statsLayout.slotW); colSlot:SetJustifyH("LEFT"); colSlot:SetText(L["stats_slot_header"]); colSlot:SetTextColor(0.7, 0.7, 0.7)
    local colItem = stp:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    colItem:SetPoint("TOPLEFT", 96, colY); colItem:SetWidth(stp.statsLayout.itemW); colItem:SetJustifyH("LEFT"); colItem:SetText(L["stats_item_header"]); colItem:SetTextColor(0.7, 0.7, 0.7)
    -- Use WoW global strings for stat names (auto-localized)
    local colCrit = stp:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    colCrit:SetPoint("TOPLEFT", 266, colY); colCrit:SetWidth(stp.statsLayout.statW); colCrit:SetJustifyH("CENTER")
    colCrit:SetText(STAT_CRITICAL_STRIKE or ITEM_MOD_CRIT_RATING_SHORT or "Crit"); colCrit:SetTextColor(1, 0.5, 0.5)
    local colHaste = stp:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    colHaste:SetPoint("TOPLEFT", 350, colY); colHaste:SetWidth(stp.statsLayout.statW); colHaste:SetJustifyH("CENTER")
    colHaste:SetText(STAT_HASTE or ITEM_MOD_HASTE_RATING_SHORT or "Haste"); colHaste:SetTextColor(0.5, 1, 0.5)
    local colMastery = stp:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    colMastery:SetPoint("TOPLEFT", 434, colY); colMastery:SetWidth(stp.statsLayout.statW); colMastery:SetJustifyH("CENTER")
    colMastery:SetText(STAT_MASTERY or ITEM_MOD_MASTERY_RATING_SHORT or "Mastery"); colMastery:SetTextColor(0.5, 0.5, 1)
    local colVersa = stp:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    colVersa:SetPoint("TOPLEFT", 518, colY); colVersa:SetWidth(stp.statsLayout.statW); colVersa:SetJustifyH("CENTER")
    colVersa:SetText(STAT_VERSATILITY or ITEM_MOD_VERSATILITY or "Versa"); colVersa:SetTextColor(1, 0.82, 0)
    stp.colSlot = colSlot
    stp.colItem = colItem
    stp.colCrit = colCrit
    stp.colHaste = colHaste
    stp.colMastery = colMastery
    stp.colVersa = colVersa

    local colSep = stp:CreateTexture(nil, "ARTWORK"); colSep:SetColorTexture(UI.lineSoft[1], UI.lineSoft[2], UI.lineSoft[3], UI.lineSoft[4]); colSep:SetHeight(2)
    colSep:SetPoint("TOPLEFT", 20, -56); colSep:SetPoint("TOPRIGHT", -20, -56)

    local stScroll = CreateFrame("ScrollFrame", "BisManagerStatsScroll", stp, "UIPanelScrollFrameTemplate")
    stScroll:SetPoint("TOPLEFT", 20, -60); stScroll:SetPoint("BOTTOMRIGHT", -38, 48)
    SkinScrollFrame(stScroll)
    stp.scrollFrame = stScroll
    stp.scrollChild = CreateFrame("Frame", nil, stScroll)
    stp.scrollChild:SetSize(620, 10); stScroll:SetScrollChild(stp.scrollChild)

    stp.noDataText = stp:CreateFontString(nil, "OVERLAY", "GameFontDisable")
    stp.noDataText:SetPoint("CENTER", 0, 0); stp.noDataText:SetText(L["stats_no_data"]); stp.noDataText:Hide()

    ----------------------------------------------------------------
    -- TAB 3: SETTINGS PANEL
    ----------------------------------------------------------------
    configFrame.settingsPanel = CreateFrame("Frame", nil, configFrame, BD_TEMPLATE)
    configFrame.settingsPanel:SetPoint("TOPLEFT", PADDING, -80); configFrame.settingsPanel:SetPoint("BOTTOMRIGHT", -PADDING, PADDING)
    ApplyBackdrop(configFrame.settingsPanel, { 0, 0, 0, 0 }, { 0, 0, 0, 0 })
    configFrame.settingsPanel:Hide()
    local sp = configFrame.settingsPanel

    sp.displayCard = CreateBentoCard(sp, L["display_header"], UI.blue)
    sp.displayCard:SetPoint("TOPLEFT", 0, 0)
    sp.displayCard:SetSize(420, 190)

    sp.tuningCard = CreateBentoCard(sp, L["slider_scale"], UI.gold)
    sp.tuningCard:SetPoint("TOPLEFT", sp.displayCard, "TOPRIGHT", GAP, 0)
    sp.tuningCard:SetPoint("RIGHT", 0, 0)
    sp.tuningCard:SetHeight(190)

    sp.actionsCard = CreateBentoCard(sp, L["actions_header"], UI.green)
    sp.actionsCard:SetPoint("TOPLEFT", 0, -(190 + GAP))
    sp.actionsCard:SetSize(420, 188)

    sp.helpCard = CreateBentoCard(sp, L["help_header"], UI.blue)
    sp.helpCard:SetPoint("TOPLEFT", sp.actionsCard, "TOPRIGHT", GAP, 0)
    sp.helpCard:SetPoint("BOTTOMRIGHT", 0, 0)

    sp.enabledCheck = CreateFrame("CheckButton", "BisManagerEnabledCheck", sp.displayCard, "UICheckButtonTemplate")
    sp.enabledCheck:SetPoint("TOPLEFT", PADDING, -40)
    SkinCheckButton(sp.enabledCheck)
    local el = sp.displayCard:CreateFontString(nil, "OVERLAY", "GameFontNormal")
    el:SetPoint("LEFT", sp.enabledCheck, "RIGHT", 4, 0); el:SetText(L["check_enabled"])
    sp.enabledCheck:SetScript("OnClick", function(self)
        if BisManager.db then BisManager.db.display.enabled = self:GetChecked() and true or false; BisManager:RefreshAll() end
    end)

    sp.showIlvlCheck = CreateFrame("CheckButton", "BisManagerShowIlvlCheck", sp.displayCard, "UICheckButtonTemplate")
    sp.showIlvlCheck:SetPoint("TOPLEFT", PADDING, -72)
    SkinCheckButton(sp.showIlvlCheck)
    local il = sp.displayCard:CreateFontString(nil, "OVERLAY", "GameFontNormal")
    il:SetPoint("LEFT", sp.showIlvlCheck, "RIGHT", 4, 0); il:SetText(L["check_show_ilvl"])
    sp.showIlvlCheck:SetScript("OnClick", function(self)
        if BisManager.db then BisManager.db.display.showIlvl = self:GetChecked() and true or false; BisManager:RefreshAll(); RefreshSlotList() end
    end)

    sp.scaleSlider = CreateSimpleSlider(sp.tuningCard, L["slider_scale"], 0.7, 1.6, 0.05, 1)
    sp.scaleSlider:SetPoint("TOPLEFT", PADDING, -44)
    sp.scaleSlider.slider:SetScript("OnValueChanged", function(_, v)
        if not BisManager.db then return end
        v = math.floor(v * 100 + 0.5) / 100; BisManager.db.display.scale = v
        sp.scaleSlider.valueText:SetText(("%.2f"):format(v)); BisManager:RefreshAll()
    end)

    sp.alphaSlider = CreateSimpleSlider(sp.tuningCard, L["slider_alpha"], 0.3, 1.0, 0.05, 1)
    sp.alphaSlider:SetPoint("TOPLEFT", PADDING, -108)
    sp.alphaSlider.slider:SetScript("OnValueChanged", function(_, v)
        if not BisManager.db then return end
        v = math.floor(v * 100 + 0.5) / 100; BisManager.db.display.alpha = v
        sp.alphaSlider.valueText:SetText(("%.2f"):format(v)); BisManager:RefreshAll()
    end)

    local snapBtn = SuccessBtn(sp.actionsCard, L["btn_snapshot"], 360, 36)
    snapBtn:SetPoint("TOP", sp.actionsCard, "TOP", 0, -50)
    snapBtn:SetScript("OnClick", function()
        local c = BisManager:SnapshotCurrentGear()
        if c > 0 then RefreshSlotList(); RefreshDetailPanel() end
    end)

    local cpBtn = InfoBtn(sp.actionsCard, L["btn_open_char"], 360, 36)
    cpBtn:SetPoint("TOP", snapBtn, "BOTTOM", 0, -10)
    cpBtn:SetScript("OnClick", function() BisManager:OpenCharacterPanel() end)

    local caBtn = DangerBtn(sp.actionsCard, L["btn_clear_all"], 360, 36)
    caBtn:SetPoint("TOP", cpBtn, "BOTTOM", 0, -12)
    caBtn:SetScript("OnClick", function() StaticPopup_Show("BisManager_CONFIRM_CLEAR_ALL") end)


    local ht = sp.helpCard:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
    ht:SetPoint("TOPLEFT", PADDING, -40); ht:SetPoint("BOTTOMRIGHT", -PADDING, PADDING); ht:SetJustifyH("LEFT"); ht:SetJustifyV("TOP"); ht:SetSpacing(2)
    ht:SetText(L["help_config_text"])

    ----------------------------------------------------------------
    -- TAB 4: PROFILES (redesigned: two sections)
    ----------------------------------------------------------------
    configFrame.profilesPanel = CreateFrame("Frame", nil, configFrame, BD_TEMPLATE)
    configFrame.profilesPanel:SetPoint("TOPLEFT", PADDING, -80); configFrame.profilesPanel:SetPoint("BOTTOMRIGHT", -PADDING, PADDING)
    ApplyBackdrop(configFrame.profilesPanel, { 0, 0, 0, 0 }, { 0, 0, 0, 0 })
    configFrame.profilesPanel:Hide()
    local pp = configFrame.profilesPanel

    local MAX_GEN_ROWS = 30
    pp.maxGeneratedRows = MAX_GEN_ROWS
    pp.generatedButtons = {}

    pp.leftProfileColumn = CreateFrame("Frame", nil, pp)
    pp.leftProfileColumn:SetPoint("TOPLEFT", 0, 0)
    pp.leftProfileColumn:SetPoint("BOTTOMLEFT", pp, "BOTTOMLEFT", 0, 74)
    pp.leftProfileColumn:SetWidth(340)

    pp.generatedSummaryCard = CreateBentoCard(pp.leftProfileColumn, L["profile_auto_title"], UI.gold)
    pp.generatedSummaryCard:SetPoint("TOPLEFT", 0, 0)
    pp.generatedSummaryCard:SetPoint("TOPRIGHT", 0, 0)
    pp.generatedSummaryCard:SetHeight(72)
    pp.generatedSummary = pp.generatedSummaryCard:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
    pp.generatedSummary:SetPoint("TOPLEFT", PADDING, -34)
    pp.generatedSummary:SetPoint("BOTTOMRIGHT", -PADDING, PADDING)
    pp.generatedSummary:SetJustifyH("LEFT")
    pp.generatedSummary:SetJustifyV("TOP")
    pp.generatedSummary:SetTextColor(0.82, 0.86, 0.9)
    pp.generatedSummary:SetText("")

    pp.generatedListContainer = CreateBentoCard(pp.leftProfileColumn, L["profile_section_generated"], UI.gold)
    pp.generatedListContainer:SetPoint("TOPLEFT", pp.generatedSummaryCard, "BOTTOMLEFT", 0, -GAP)
    pp.generatedListContainer:SetPoint("BOTTOMRIGHT", pp.leftProfileColumn, "BOTTOMRIGHT", 0, 0)
    pp.genHeader = pp.generatedListContainer.title

    local function ResizeProfileLeftColumn(self, _, height)
        height = height or self:GetHeight() or 0
        if height <= GAP then
            return
        end
        pp.generatedSummaryCard:SetHeight(math.floor((height - GAP) / 6))
    end
    pp.leftProfileColumn:SetScript("OnSizeChanged", ResizeProfileLeftColumn)
    ResizeProfileLeftColumn(pp.leftProfileColumn)

    pp.generatedEmptyText = pp.generatedListContainer:CreateFontString(nil, "OVERLAY", "GameFontDisable")
    pp.generatedEmptyText:SetPoint("CENTER"); pp.generatedEmptyText:SetText(L["profile_no_generated"]); pp.generatedEmptyText:Hide()

    pp.generatedScroll = CreateFrame("ScrollFrame", "BisManagerGeneratedProfilesScroll", pp.generatedListContainer, "UIPanelScrollFrameTemplate")
    pp.generatedScroll:SetPoint("TOPLEFT", PADDING, -40)
    pp.generatedScroll:SetPoint("BOTTOMRIGHT", -24, 50)
    SkinScrollFrame(pp.generatedScroll)

    pp.generatedContent = CreateFrame("Frame", nil, pp.generatedScroll)
    pp.generatedContent:SetSize(300, MAX_GEN_ROWS * (36 + GAP))
    pp.generatedScroll:SetScrollChild(pp.generatedContent)

    for i = 1, MAX_GEN_ROWS do
        local btn = CreateFrame("Button", nil, pp.generatedContent, BD_TEMPLATE)
        btn:SetSize(284, 36); btn:SetPoint("TOPLEFT", 0, -(i - 1) * (36 + GAP))
        btn:RegisterForClicks("LeftButtonUp", "RightButtonUp")
        btn.text = btn:CreateFontString(nil, "OVERLAY", "GameFontHighlight")
        btn.text:SetPoint("TOPLEFT", PADDING, -7); btn.text:SetPoint("RIGHT", -PADDING, 0); btn.text:SetJustifyH("LEFT")
        btn.text:SetWordWrap(false)
        btn.metaText = btn:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
        btn.metaText:SetPoint("TOPLEFT", btn.text, "BOTTOMLEFT", 0, -1)
        btn.metaText:SetPoint("RIGHT", -12, 0)
        btn.metaText:SetJustifyH("LEFT")
        btn.metaText:SetTextColor(0.56, 0.68, 0.78)
        btn.hl = btn:CreateTexture(nil, "HIGHLIGHT"); btn.hl:SetAllPoints(); btn.hl:SetColorTexture(0.36, 0.78, 1, 0.15)
        SkinButton(btn)
        -- Source URL text
        btn.urlText = btn:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
        btn.urlText:SetPoint("LEFT", 12, -11); btn.urlText:SetWidth(244)
        btn.urlText:SetJustifyH("LEFT"); btn.urlText:SetWordWrap(false)
        btn.urlBtn = CreateFrame("Button", nil, btn)
        btn.urlBtn:SetAllPoints(btn)
        btn.urlBtn:EnableMouse(false)
        btn.urlBtn:SetScript("OnClick", nil)
        btn.urlBtn:SetScript("OnEnter", function(self)
            if not btn.url or btn.url == "" then return end
            GameTooltip:SetOwner(self, "ANCHOR_TOPLEFT")
            GameTooltip:AddLine(btn.text and btn.text:GetText() or "", 1, 1, 1, true)
            if btn.metaText and btn.metaText:GetText() ~= "" then
                GameTooltip:AddLine(btn.metaText:GetText(), 0.56, 0.68, 0.78, true)
                GameTooltip:AddLine(" ")
            end
            GameTooltip:AddLine(L["profile_tooltip_link"], 0.8, 0.8, 0.8, true)
            GameTooltip:AddLine(btn.url, 0.36, 0.78, 1, true)
            GameTooltip:AddLine(L["profile_tooltip_right_open_link"], 0.8, 0.8, 0.8, true)
            GameTooltip:Show()
        end)
        btn.urlBtn:SetScript("OnLeave", GameTooltip_Hide)
        btn.urlBtn:Hide()
        btn:Hide()
        pp.generatedButtons[i] = btn
    end

    local resetGenBtn = DangerBtn(pp.generatedListContainer, L["btn_reset_generated"], 190, 28)
    resetGenBtn:SetPoint("BOTTOM", pp.generatedListContainer, "BOTTOM", 0, 14)
    resetGenBtn:SetScript("OnClick", function() StaticPopup_Show("BisManager_CONFIRM_RESET_GENERATED") end)

    local MAX_USR_ROWS = 8
    pp.maxUserRows = MAX_USR_ROWS
    pp.userButtons = {}

    pp.userListContainer = CreateBentoCard(pp, L["profile_section_user"], UI.blue)
    pp.userListContainer:SetPoint("TOPLEFT", pp.leftProfileColumn, "TOPRIGHT", GAP, 0)
    pp.userListContainer:SetPoint("BOTTOMRIGHT", 0, 74)

    pp.userEmptyText = pp.userListContainer:CreateFontString(nil, "OVERLAY", "GameFontDisable")
    pp.userEmptyText:SetPoint("CENTER"); pp.userEmptyText:SetText(L["profile_no_user"]); pp.userEmptyText:Hide()

    for i = 1, MAX_USR_ROWS do
        local btn = CreateFrame("Button", nil, pp.userListContainer, BD_TEMPLATE)
        btn:SetPoint("TOPLEFT", PADDING, -(i - 1) * (30 + GAP) - 40)
        btn:SetPoint("RIGHT", -48, 0)
        btn:SetHeight(30)
        btn.text = btn:CreateFontString(nil, "OVERLAY", "GameFontHighlight")
        btn.text:SetPoint("LEFT", 12, 0); btn.text:SetPoint("RIGHT", -30, 0); btn.text:SetJustifyH("LEFT")
        btn.hl = btn:CreateTexture(nil, "HIGHLIGHT"); btn.hl:SetAllPoints(); btn.hl:SetColorTexture(0.36, 0.78, 1, 0.15)
        SkinButton(btn)
        btn.delBtn = CreateFrame("Button", nil, pp.userListContainer, BD_TEMPLATE)
        btn.delBtn:SetSize(20, 20); btn.delBtn:SetPoint("LEFT", btn, "RIGHT", 2, 0)
        SkinDeleteIcon(btn.delBtn, 11)
        btn.delBtn:Hide()
        btn:Hide()
        pp.userButtons[i] = btn
    end

    pp.profileActionsCard = CreateBentoCard(pp, nil, UI.green)
    pp.profileActionsCard:SetPoint("BOTTOMLEFT", 0, 0)
    pp.profileActionsCard:SetPoint("BOTTOMRIGHT", 0, 0)
    pp.profileActionsCard:SetHeight(62)

    local newProfileEditBox = CreateFrame("EditBox", "BisManagerNewProfileEditBox", pp.profileActionsCard, EDITBOX_TEMPLATE)
    newProfileEditBox:SetSize(250, 24); newProfileEditBox:SetPoint("LEFT", 16, 0)
    newProfileEditBox:SetAutoFocus(false); newProfileEditBox:SetMaxLetters(64)
    SkinEditBox(newProfileEditBox)

    local newProfileBtn = SuccessBtn(pp.profileActionsCard, L["btn_new_profile"], 126, 30)
    newProfileBtn:SetPoint("LEFT", newProfileEditBox, "RIGHT", 10, 0)
    newProfileBtn:SetScript("OnClick", function()
        local name = newProfileEditBox:GetText()
        if name and name:match("%S") then
            BisManager:GetOrCreateProfile(name)
            BisManager:SetActiveProfile(name)
            newProfileEditBox:SetText("")
            RefreshProfilesPanel(); RefreshSlotList(); RefreshDetailPanel()
        end
    end)
    newProfileEditBox:SetScript("OnEnterPressed", function(self)
        newProfileBtn:GetScript("OnClick")()
        self:ClearFocus()
    end)

    local copyBtn = InfoBtn(pp.profileActionsCard, L["btn_profile_copy"], 126, 30)
    copyBtn:SetPoint("LEFT", newProfileBtn, "RIGHT", 8, 0)
    copyBtn:SetScript("OnClick", function()
        local name = newProfileEditBox:GetText()
        if name and name:match("%S") then
            BisManager:CopyActiveProfileTo(name)
            newProfileEditBox:SetText("")
            RefreshProfilesPanel()
        end
    end)

    local resetAllBtn = DangerBtn(pp.profileActionsCard, L["btn_reset_profiles"], 190, 30)
    resetAllBtn:SetPoint("RIGHT", -16, 0)
    resetAllBtn:SetScript("OnClick", function() StaticPopup_Show("BisManager_CONFIRM_RESET_PROFILES") end)

    ----------------------------------------------------------------
    -- TAB 5: IMPORT / EXPORT
    ----------------------------------------------------------------
    configFrame.importPanel = CreateFrame("Frame", nil, configFrame, BD_TEMPLATE)
    configFrame.importPanel:SetPoint("TOPLEFT", PADDING, -80); configFrame.importPanel:SetPoint("BOTTOMRIGHT", -PADDING, PADDING)
    ApplyBackdrop(configFrame.importPanel, { 0, 0, 0, 0 }, { 0, 0, 0, 0 })
    configFrame.importPanel:Hide()
    local ip = configFrame.importPanel

    ip.topCard = CreateBentoCard(ip, L["import_header"], UI.blue)
    ip.topCard:SetPoint("TOPLEFT", 0, 0)
    ip.topCard:SetPoint("TOPRIGHT", 0, 0)
    ip.topCard:SetHeight(72)

    ip.profileLabel = ip.topCard:CreateFontString(nil, "OVERLAY", "GameFontNormal")
    ip.profileLabel:SetPoint("TOPLEFT", PADDING, -40); ip.profileLabel:SetText(L["profile_target"])

    ip.profileEditBox = CreateFrame("EditBox", "BisManagerImportProfileEditBox", ip.topCard, EDITBOX_TEMPLATE)
    ip.profileEditBox:SetSize(180, 22); ip.profileEditBox:SetPoint("LEFT", ip.profileLabel, "RIGHT", 8, 0)
    ip.profileEditBox:SetAutoFocus(false); ip.profileEditBox:SetMaxLetters(64)
    SkinEditBox(ip.profileEditBox)

    local editBg = CreateBentoCard(ip, L["import_export_textarea_title"], UI.gold)
    editBg:SetPoint("TOPLEFT", ip.topCard, "BOTTOMLEFT", 0, -GAP)
    editBg:SetPoint("BOTTOMLEFT", 0, 0)
    editBg:SetWidth(520)

    local tutorialCard = CreateBentoCard(ip, L["import_export_tutorial_title"], UI.blue)
    tutorialCard:SetPoint("TOPLEFT", editBg, "TOPRIGHT", GAP, 0)
    tutorialCard:SetPoint("BOTTOMRIGHT", 0, 0)

    local tutorialText = tutorialCard:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
    tutorialText:SetPoint("TOPLEFT", PADDING, -40)
    tutorialText:SetPoint("BOTTOMRIGHT", -PADDING, PADDING)
    tutorialText:SetJustifyH("LEFT")
    tutorialText:SetJustifyV("TOP")
    tutorialText:SetSpacing(2)
    tutorialText:SetText(L["import_instructions"])

    local textAreaBg = CreateFrame("Frame", nil, editBg, BD_TEMPLATE)
    textAreaBg:SetPoint("TOPLEFT", PADDING, -40)
    textAreaBg:SetPoint("BOTTOMRIGHT", -PADDING, 54)
    ApplyBackdrop(textAreaBg, UI.input, UI.line, UI.round.card)

    local isf = CreateFrame("ScrollFrame", "BisManagerImportScroll", textAreaBg, "UIPanelScrollFrameTemplate")
    isf:SetPoint("TOPLEFT", 8, -8); isf:SetPoint("BOTTOMRIGHT", -28, 8)
    SkinScrollFrame(isf)
    local ieb = CreateFrame("EditBox", "BisManagerImportEditBox", isf)
    ieb:SetMultiLine(true); ieb:SetAutoFocus(false); ieb:SetFontObject("ChatFontNormal"); ieb:SetWidth(430)
    ieb:SetScript("OnEscapePressed", function(self) self:ClearFocus() end)
    isf:SetScrollChild(ieb)
    ip.editBox = ieb

    ip.statusText = editBg:CreateFontString(nil, "OVERLAY", "GameFontHighlight")
    ip.statusText:SetPoint("BOTTOMLEFT", 246, 18); ip.statusText:SetPoint("RIGHT", -18, 0); ip.statusText:SetJustifyH("LEFT"); ip.statusText:SetText("")

    local impBtn = SuccessBtn(editBg, L["btn_import"], 112, 32)
    impBtn:SetPoint("BOTTOMLEFT", 16, 14)
    impBtn:SetScript("OnClick", function()
        local text = ieb:GetText()
        local profileName = ip.profileEditBox:GetText()
        if not text or text:match("^%s*$") then ip.statusText:SetText(L["import_empty"]); return end
        local c = BisManager:ImportBiSString(text, profileName)
        if c > 0 then
            if profileName and profileName:match("%S") then BisManager:SetActiveProfile(profileName) end
            ip.statusText:SetText(L["import_success"]:format(c))
            RefreshSlotList(); RefreshDetailPanel(); RefreshProfilesPanel()
        else
            ip.statusText:SetText(L["import_fail"])
        end
    end)

    local expBtn = InfoBtn(editBg, L["btn_export"], 112, 32)
    expBtn:SetPoint("LEFT", impBtn, "RIGHT", 8, 0)
    expBtn:SetScript("OnClick", function()
        local profileName = ip.profileEditBox:GetText()
        local s = BisManager:ExportBiSString(profileName and profileName:match("%S") and profileName or nil)
        if s ~= "" then
            ieb:SetText(s); ieb:HighlightText(); ieb:SetFocus()
            ip.statusText:SetText(L["export_success"])
        else
            ip.statusText:SetText(L["export_empty"])
        end
    end)

    ----------------------------------------------------------------
    -- Init
    ----------------------------------------------------------------
    SwitchTab("slots")
    configFrame:Hide()
    return configFrame
end

------------------------------------------------------------------------
-- Public API
------------------------------------------------------------------------

function BisManager:ToggleConfigUI()
    if not configFrame then CreateConfigFrame() end
    if configFrame:IsShown() then configFrame:Hide()
    else configFrame:Show(); SwitchTab("slots") end
end

function BisManager:OpenConfigForSlot(slotKey)
    if not configFrame then CreateConfigFrame() end
    configFrame:Show()
    SwitchTab("slots")
    selectedSlotKey = slotKey
    RefreshSlotList()
    RefreshDetailPanel()
end

function BisManager:RefreshConfigUI()
    if configFrame and configFrame:IsShown() then
        RefreshSlotList(); RefreshSettingsPanel(); RefreshImportPanel(); RefreshProfilesPanel(); RefreshDetailPanel()
    end
end

